### ISSUE TITLE
SelectMany chaining not working, cause wrong SQL generation

### ISSUE THREAD

**Issue by tanwarsatya** [Azure/azure-cosmos-dotnet-v2#177]
Hi,

When using SelectMany in a chain fashion, documentdb client is throwing an error, I am using  "Microsoft.Azure.DocumentDB" version="1.10.0  nugget.

'System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.Documents.DocumentClientException: Message: {"errors":[{"severity":"Error","location":{"start":71,"end":74},"code":"SC2021","message":"The input set name or alias 'tmp' is specified more than once in the FROM clause."}]}'

**Generated SQL -** 

SELECT VALUE tmp FROM root JOIN tmp IN root[\"TransportStoppages\"] JOIN tmp IN tmp[\"PatronId\"] WHERE (((root[\"type\"] = \"TransportRoute\") AND (root[\"organizationid\"] = \"b077007f-6e64-4074-bd2b-c9500d89bef8\")) AND (root[\"id\"] = \"85e3bec7-72d5-4576-8f42-558f7d9891a0\")) 

I am using repository pattern to execute below mentioned query

            var result = (await this.repository.WhereAsync(p => p.type.Equals(typeof(TransportRoute).Name)
                                                                 && p.organizationid.Equals(organizationid)
                                                                 && p.Id.Equals(routeid) 
                                                           ))
                                                           .SelectMany(a => a.TransportStoppages)
                                                           .SelectMany(t => t.PatronId);
     

**The structure of document is below -** 
            
id :  85e3bec7-72d5-4576-8f42-558f7d9891a0,
RouteNumber :  1,
RegistrationNumber :  DL 5C3442,
DriverId :  5f121a8f-05cb-4e36-bb80-14e86bc194f8,
CoordinatorId :  d55938a5-2232-468b-9ac8-63fbe966df6a,
RouteStaffId :  e31b5213-3a36-4e18-a1b8-682a49d68f57,
Description :  transport route 1,
TransportStoppages : [{Sequence :  1,
Name :  Tilak Nagar,
PatronId : [ 
 s31b5213-3a36-5e18-a1b8-662a49d68f57
],
Lattitude :  28.636588782704045,
Longitude :  77.094503288269,
PickupTime :  8:00,
DropTime :  2:10,
Description :  Tilak Nagar Stoppage,
id :  d55938a5-2232-468b-9ac8-63fbe966123a,
organizationid :  b077007f-6e64-4074-bd2b-c9500d89bef8,
type :  TransportStoppage,
createdate :  2016-11-23T03:30:09.007Z,
lastupdated :  2016-11-23T03:30:09.007Z
}
],
Remarks :  Transport route,
organizationid :  b077007f-6e64-4074-bd2b-c9500d89bef8,
type :  TransportRoute,
createdate :  2016-11-23T03:29:30.195Z,
lastupdated :  2016-11-23T03:29:30.195Z

**Comment by jonathanfishbein1** [comment]
I'm also getting this error

**Comment by jonathanfishbein1** [comment]
@tanwarsatya the documentation here will help 

https://docs.microsoft.com/en-us/azure/documentdb/documentdb-sql-query#linq-to-documentdb-sql


scroll to Nesting

**Comment by brightertools** [comment]
I am getting this same error with nested SelectMany's to filter on child elements, I have looked at the link and scrolled to Nesting, I am pretty sure I am only using the correct line methods (I get an error if I dont) but still dont understand why I get the error: 

"The input set name or alias 'tmp' is specified more than once in the FROM clause."

Can someone explain in more details?

Thanks.

**Comment by PhotoAtomic** [comment]
looks like the Expression is translated to the wrong query when select many are nested, the outermost object reference is called tmp while the innermost reference "kind of" maintain the name given in the expression but in the wrong way

for example i've object of this kind

`{
    "$id": "1",
    "$type": "SolventDB.Model.Data.Zone, SolventDB.Model",
    "id": "b262d773-eb25-4425-b5fc-a6f185fcc75d",
    "Name": "Denios B",
    "Capacity": 10,
    "Cotterman": null,
    "Rules": [
        {
            "$id": "2",
            "$type": "SolventDB.Model.Data.MaxLitersOfFlamableSolvent, SolventDB.Model",
            "Id": "0ffea69a-b3ec-4a53-9601-b93c4facd51c",
            "Type": "MaxLitersOfFlamableSolvent",
            "SumValue": 4
        },
        {
            "$id": "3",
            "$type": "SolventDB.Model.Data.MaxAmountForRegister, SolventDB.Model",
            "Type": "MaxAmountForRegister",
            "Id": "7112ffac-c787-44b2-806a-b8e1d378d8ed",
            "MaxValue": 23,
            "Register": {
                "$id": "4",
                "$type": "SolventDB.Model.Data.Register, SolventDB.Model",
                "id": "c12acc02-828c-4970-8098-5481d5d1b0f7",
                "Name": "Spiriti"
            }
        }
    ],
    "_rid": "sr5nAPfo620BAAAAAAAAAA==",
    "_self": "dbs/sr5nAA==/colls/sr5nAPfo620=/docs/sr5nAPfo620BAAAAAAAAAA==/",
    "_etag": "\"00000000-0000-0000-9076-a4c776ae01d4\"",
    "_attachments": "attachments/",
    "_ts": 1544439234
}`

and a query like this

`var solvenTypeRule = context.RepositoryOf<Zone>() 
                .SelectMany(zone=> zone.Rules.SelectMany(r=>((MaxAmountForSolventType)r).SolventType.Registers).Where(r=>r.Id== RegisterId).Select(x=>zone))
                .ToArray();`

and the expression is translated to this query
`SELECT VALUE tmp FROM root JOIN r IN root["Rules"] JOIN tmp IN r["SolventType"]["Registers"] WHERE (tmp["id"] = "c12acc02-828c-4970-8098-5481d5d1b0f7")`

and this is wrong because should be at least

`SELECT VALUE r FROM root JOIN r IN root["Rules"] JOIN tmp IN r["SolventType"]["Registers"] WHERE (tmp["id"] = "c12acc02-828c-4970-8098-5481d5d1b0f7")`

to be semantically the same, but "r" is the innermost reference in the query therefore looks like the "tmp" and "r" name are swapped 

please opensource the project so we could provide fix for this

**Comment by khdang** [comment]
This should be fixed in SDK version 2.2.3 and later. Thanks.

**Comment by tanwarsatya** [comment]
We moved from cosmos dB to Postgres.
