### ISSUE TITLE
CreateDocumentQuery fails to Serialize with LINQ

### ISSUE THREAD

**Issue by JLunda** [Azure/azure-cosmos-dotnet-v2#306]
I have the following C# code:

```
IQueryable<Document> users = client.CreateDocumentQuery(UserCollectionId);
            foreach (var u in users)
            {
                //we will do something based off of the document.
                string doc = u.ToString();
            }
            return null;
```

This fails, however, to even serialize from the query to the Document type when it reaches the point of figuring out the var u in users.  Trying to type this more strongly, where I use my own simple User POCO also fails.

Catching the exception in Visual Studio shows the following details:

-		InnerException	{"Failed to parse the value '' as ResourceId.\r\nActivityId: 80000043-0000-f900-b63f-84710c7967bb"}	System.Exception {Microsoft.Azure.Documents.BadRequestException}
-		ResponseHeaders	{System.Collections.Specialized.NameValueCollection}	System.Collections.Specialized.NameValueCollection
		[0]	"x-ms-activity-id"	string
-		Source	"Microsoft.Azure.Documents.Client"	string
-		StackTrace	"   at Microsoft.Azure.Documents.ResourceId.Parse(String id)\r\n   at Microsoft.Azure.Documents.Common.CollectionCache.ResolveByRidAsync(String resourceId, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Documents.Common.CollectionCache.<ResolveCollectionAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextFactory.<CreateDocumentQueryExecutionContextAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<CreateDocumentQueryExecutionContextAsync>d__12.MoveNext()"	string
-		TargetSite	{Microsoft.Azure.Documents.ResourceId Parse(System.String)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}

From what I gather, the ActivityID or ResourceID is failing to parse, or the ActivityID is attempting to be parsed as the ResourceID and causing a failure.  Is this a bug that needs to be fixed?

As a workaround, the following seems to work currently, but a fix to the above would be appreciated, as it is much easier to write.

```
var dbUsers = await client.ReadDocumentFeedAsync(UriFactory.CreateDocumentCollectionUri(DatabaseId,UserCollectionId));

            List<Models.User> users = new List<Models.User>();
            foreach(var u in dbUsers)
            {
                users.Add(new Models.User() { firstName = u.firstName, lastName = u.lastName, userName = u.userName });
            }
           return users;
```

**Comment by ealsur** [comment]
@JLunda What version and which Nuget package are you using?

**Comment by JLunda** [comment]
> @JLunda What version and which Nuget package are you using?

@ealsur I am using the latest version of 1.15.0 for the DocumentDB NuGet package, and version 8.0.3 of Newtonsoft.Json.  I have read in other posts that higher versions of the Newtonsoft.Json package may not play well with DocumentDB, so I have it at the minimum version that any of my packages can handle, namely the Microsoft.Bot.Builder package v. 3.8.4, since 3.8.5 causes a different issue with Card Dialogs, but I do not want to use this thread to troubleshoot that.

**Comment by kirankumarkolli** [comment]
@JLunda what was the value of 'UserCollectionId' passed in first sample? I guess its malformed and server is throwing it out. 

Also please note that cosmos DB only support either SelfLink or AltLink. Make sure that UserCollectionId matched one of them.

**Comment by JLunda** [comment]
Closing, since this issue is all the way from 2017 and Cosmos DB has evolved considerably since then. This issue would not apply anymore.
