### ISSUE TITLE
Orderby returns 1 row while orderbydescending works

### ISSUE THREAD

**Issue by dagtveit** [Azure/azure-cosmos-dotnet-v2#368]
Orderby returns 1 row while orderbydescending works. they both generate valid querys 
SELECT * FROM root WHERE (root["type"] = "report") ORDER BY root["datoTs"] DESC 
SELECT * FROM root WHERE (root["type"] = "report") ORDER BY root["datoTs"] ASC 

But the order by returns 1 row only. while the orderbydescending works fine. 
there is indexes on the collection cause i have a older site working on the same database with sql query instead of linq and that works sorting both ways.

**Comment by khdang** [comment]
@bchong95 can you help to look at this issue?

**Comment by bchong95** [comment]
The rest of the results might be in the following continuations of the query. Are you using the ExecuteNextAsync() pattern? If so you can wrap it in a "while documentQuery.HasMoreResults" loop and see of the rest of your documents are there.

**Comment by dagtveit** [comment]
srry for the late reply it was lost in all the emails. i doo use some extensions to linq that is implementing continuationtoken.  i ripped of a project that i cant remember whare now. and the name. but it have you making provider and service and iservice to implement it with asp.net core2. and in the extension methods there is one method for takeone and one called topagedresults. and that method if i remember correctly is implementing the executenextasync

 public static async Task<PagedResults<T>> ToPagedResults<T>(this IQueryable<T> source)
        {
            var documentQuery = source.AsDocumentQuery();
            
            var results = new PagedResults<T>();

            try
            {
                var queryResult = await documentQuery.ExecuteNextAsync<T>();
                
                
                if (!queryResult.Any())
                {
                    return results;
                }
                results.ContinuationToken = queryResult.ResponseContinuation;
                results.Results.AddRange(queryResult);
            }
            catch
            {
                //documentQuery.ExecuteNextAsync throws an Exception if there are no results
                return results;


all this is working fine with paged results. i have set the feed options to 10 rows. and it returns 10 and i can ask again for the next results. but when doing the order by it onlt returns 1 row even if the feedoptions is 10.

**Comment by dagtveit** [comment]
I may found a culprit i am not shure if its related. but if i have a document in the document db that has an empty value in the order by field linq query completly excludes everything

**Comment by bchong95** [comment]
@dagtveit as you have experienced first hand FeedOptions.MaxItemCount = 10 only guarantees that you will at most get 10 items per continuation, but still means you could get an empty continuation.

This blog post explains how you can reliably page through the results:

https://www.kevinkuszyk.com/2016/08/19/paging-through-query-results-in-azure-documentdb/
