### ISSUE TITLE
DocumentClient TransientFaultHandling in .NET Standard?

### ISSUE THREAD

**Issue by t03apt** [Azure/azure-cosmos-dotnet-v2#432]
Hi!

Are there any plans to migrate [Microsoft.Azure.Documents.Client.TransientFaultHandling](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.TransientFaultHandling/) to .NET Standard?

**Comment by awcab** [comment]
Hey @t03apt it's now [included in the SDK](https://stackoverflow.com/questions/43261193/documentdb-transientfaulthandling-for-core/43276925#43276925)!

**Comment by t03apt** [comment]
@awcab I think it is not. RetryOptions is not the same. It has two integer parameters and that's all. But TransientFaultHandling provided a way to implement custom retry strategies for example exponential retries.
