### ISSUE TITLE
Select query not working when trying to query lazily using DocumentQuery

### ISSUE THREAD

**Issue by slnksachin** [Azure/azure-cosmos-dotnet-v2#477]
Any idea, if select method is going to be supported any time soon

```
{
    "errorCode": "DocumentQueryException",
    "errorMessage": "Method 'Select' is not supported., documentdb-dotnet-sdk/1.21.1 Host/64-bit MicrosoftWindowsNT/6.2.9200.0"
}
```

**Comment by slnksachin** [comment]
And also It would be great help, if someone can please help me out in finding out what all quering methods can be used with DocumentQuery

**Comment by slnksachin** [comment]
@reddy6ue Sorry, man but it doesn't help much, it says 
![image](https://user-images.githubusercontent.com/1255121/38803020-921476f4-418b-11e8-9569-b2edc0083938.png)
These all linq operators are working and I am not able to use select query as you can see here
```
{
    "errorCode": "DocumentQueryException",
    "errorMessage": "Method 'Select' is not supported., documentdb-dotnet-sdk/1.21.1 Host/64-bit MicrosoftWindowsNT/6.2.9200.0"
}
```

**Comment by slnksachin** [comment]
Also when Skip and Take will be supported ?

**Comment by khdang** [comment]
@slnksachin can you please share the code that has the error?

**Comment by slnksachin** [comment]
@khdang never mind. I found out I was using select inside where lambda which was causing the issues and I guess that kinda thing is not supported for now

**Comment by khdang** [comment]
Select inside Where lambda as described above is now supported in release 2.2.0. Please give it a try again.
