### ISSUE TITLE
Upload the DocumentDb client source code here

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v2#497]
I was happy to learn that DocumentDb was finally going to support bulk operations. So naturally, I figured I'd try it out, by loading up its Nuget... Microsoft.Azure.CosmosDB.BulkExecutor To my dismay, but not surprise, I quickly discovered the package only targets full framework and not .netstandard.

It's 2018 right?

Can you guys just please upload the client code here? If the Service Fabric guys can release their source code, there's absolutely no reason why you can't release yours. I don't even know what to say anymore.

**Comment by rnagpal** [comment]
Hi Jack, 
 
We have plans to target .NET Standard for the Bulk Import library and it should be around end of June. We are also evaluating to open source this on Github so that community can contribute to it.

**Comment by jackbond** [comment]
Evaluating? What's there to evaluate? Your library is a light wrapper for a bunch of http calls. It does not have a scintilla of intellectual property. Despite that, your team...

Seems incapable of fixing the DLL interop bug
Ignored the DateTimeOffset bug, which corrupted data, for ages
Is absolutely clueless in regards to how to properly release Nuget packages
And now has released a library which can't be targeted by .netcore

The level of incompetence is STAGGERING. It's embarrassing. Who the heck is running this show?

**Comment by kirillg** [comment]
Jack,  I lead the Cosmos DB SDK team. We respect your passionate point of view. However let me once again remind you that we expect you to follow this code of conduct on Microsoft managed OSS projects. https://opensource.microsoft.com/codeofconduct/ and be professional in your comments. As for the issues:
1) NuGet does not deal well with interop dlls, as acknowledged by NuGet team. Our plan is to get rid of the interop dll from most code paths.
2) I'm not sure what specific DTO bug you're referring to, but I gather it is resolved
3) The unified standard package that will also target 2.0 and 1.6 is in the works. 
4) I believe Rajesh already shared that bulk executor library will support .net standard. This Nuget package is a result of the work with a bunch of customers that did not use/did not need .NET Standard - we saw no reason to delay the release on supporting .net standard. We will also OSS the bulk executor, pending certain refactoring to remove it's dependency on private APIs. 

Let me know if you have more questions - you can also DM me /  happy to chat on the phone.

**Comment by jackbond** [comment]
1) How many developer hours have been wasted because your team has been incapable of resolving the interop.dll issue?

2) The DTO bug, which should have never made it into production, but for the obvious lack of sufficient unit testing, corrupted data and was ignored by your team for over a year.

3) You guys released a unified Nuget package a month or so back which had a ZERO percent chance of working. ZERO. It had gone through ZERO testing. I discovered the bug in LESS THAN AN HOUR, and then you guys subsequently yanked the package.

4) It's difficult to understand why in 2018, .netstandard was not the target framework to begin with. If the source code was available, perhaps it would be easier to understand.

All these issues aside, there is no debate that the unified nuget package you guys put out a month or so ago was a complete disaster. How did that happen? Was anyone fired? Was an apology issued? What steps have been taken to ensure that it won't happen again?

**Comment by AArnott** [comment]
@kirillg @rnagpal I'm happy to hear you are working on this. You estimate of June could use an update. What's your latest ETA? I've built a tool based on `Microsoft.Azure.CosmosDB.BulkExecutor` and I need it to run on .NET Core in the next couple months.

Thanks.

**Comment by jackbond** [comment]
Any progress on the .netstandard version of BulkExecutor?

**Comment by jackbond** [comment]
@rnagpal Any updates? Thanks.

**Comment by jackbond** [comment]
@rnagpal Awesome. I can wait a few more days. Thanks.

**Comment by rnagpal** [comment]
Hi @jackbond : We release a preview yesterday : https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/2.0.0-preview Please give it a try and let us know your feedback if any.

**Comment by AArnott** [comment]
Is this issue tracking open sourcing the SDK, or making it target .NET Core? If the latter, can we rename the issue please?

**Comment by jackbond** [comment]
Here we are a year later and still no RELEASED version which targets standard. I see 2.2.0-preview2 was released a month ago. Can we get a FIRM commitment that a non-preview version will be released in the next month?

**Comment by christopheranderson** [comment]
This issue has gone off topic a bit. v3 client source code is open source here: https://github.com/Azure/azure-cosmos-dotnet-v3

v3 is also what will target .net standard 2.0, so any discussion related to that should go there.
