### ISSUE TITLE
Update documentation to indicate that DocumentClient has to be used as a singleton instance.

### ISSUE THREAD

**Issue by faso** [Azure/azure-cosmos-dotnet-v2#499]
I believe this is very important. Right now the only indication of that is a single points in a blog post about performance tips.

See issue: https://github.com/Azure/azure-documentdb-dotnet/issues/495

**Comment by kirankumarkolli** [comment]
@faso just to clarify are you suggesting to include it in DocumentClient constructor documentation?

**Comment by faso** [comment]
@kirankumarkolli Yes, definitely. And also to the "Get Started" articles, like this one, but that's probably out of scope for this repo:

https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-dotnetcore-get-started
