### ISSUE TITLE
It can take 5 minutes to receive a 429 (or other result)

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-cosmos-dotnet-v2#517]
I'm using Cosmos DB Table API with the old table storage sdk because https://github.com/Azure/azure-documentdb-dotnet/issues/344

I'm firing off around 9k requests all at once.  Retrieve by PK & RK.  Often, it stalls.  I started looking for help here: https://stackoverflow.com/questions/50575304/cosmos-db-table-requests-stall-when-parallelized

In my further experiments, I captured this scenario:
1) Sent 10k requests 
2) 9997 completed basically instantly (which is why I wanna use cosmos db!!! 🥇 👍 )
3) 5 minutes passed
4) My custom RetryHandler gets fired and captures an error:
...(EndTime-StartTime) = 5 minutes, 42 seconds
...HttpStatusCode = 429
...StorageException: Unable to read data from the transport connection
......Inner... IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host...

Clearly:
1) The server responded, because there's a 429 response
2) The server probably responded within milliseconds (guessing)
3) The client received and read the response

![snap](https://user-images.githubusercontent.com/39773384/40733740-48650e24-63eb-11e8-8072-16bbed0825ee.png)

Why does it take so long for the request to fail, if it's received a 429?

Why does it wait for the connection to be closed by Azure?  Did Azure not send the entire response and it left the client hanging?  Is there a client-side bug?  Why why why :)

**Comment by joshlang** [comment]
I left a workload (100000's of transactions) running overnight.  Bumped up the RPU's so I didn't get any 429 errors.  One request got stuck for 10+ hours without timing out.

await Table.ExecuteAsync(TableOperation.Retrieve("aaaa", "bbbb"));
...10 hours and the task never returned!?!

Disabling the Ethernet adapter under Control Panel immediately caused the task to complete.

**Comment by kirankumarkolli** [comment]
@joshlang is the client host/VM co-located with in the same region? Is the client azure VM or local development box?

**Comment by wmengmsft** [comment]
@joshlang , looks like that example above server received the request and processed it timely. Client read the HTTP response headers from the connection but failed to read the remainder from the connection. I believe 5 minutes is the default MaxExecutionTime for the CoreCLR storage SDK, so you are hitting that timeout. As suggested by mirobers in the other issue, you can reduce this timeout to let it fail faster so you can retry.

To help us isolate/eliminate this being a server side issue:
 - Can you reproduce this against an Azure Storage Table connection string?
 - Can you reproduce this against a Cosmos DB Table connection string, but at a different region?
 - Can you reproduce this using roughly the same code but uses the version of Storage SDK on full .Net?

Also, can you share a couple more details on your runtime environment? Storage SDK version, CoreCLR version, OS name & version, name of the Cosmos DB account,

**Comment by joshlang** [comment]
I'll spend some time and try to recreate the issue.  My quick attempts failed, but I'm using a different environment at the moment.  Will follow up with results later today.

**Comment by joshlang** [comment]
Here's a minimal repo:


`
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Table;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var table = CloudStorageAccount.Parse("...........")
                .CreateCloudTableClient()
                .GetTableReference("testingdata");
            await table.CreateIfNotExistsAsync();

            var tasks = new List<Task<TableResult>>();
            long seq = DateTime.UtcNow.Ticks;
            Console.WriteLine("Creating tasks...");
            var threads = Enumerable.Range(0, 50).Select(t => new Thread(() =>
            {
                var stuff = Enumerable.Range(0, 250)
                    .Select(x => table.ExecuteAsync(TableOperation.Retrieve($"abc{Interlocked.Increment(ref seq)}", $"Whatever")))
                    .ToList();
                lock (tasks)
                    tasks.AddRange(stuff);
            })).ToList();
            var start = DateTime.UtcNow;
            foreach (var t in threads)
                t.Start();
            foreach (var t in threads)
                t.Join();
            Console.WriteLine($"{tasks.Count} retrieve tasks created in {DateTime.UtcNow.Subtract(start)}");
            while (true)
            {
                await Task.Delay(1000);
                if (tasks.All(t => t.IsCompleted))
                    break;
                Console.WriteLine($"{tasks.Count(t => t.IsCompleted)}/{tasks.Count} tasks finished in {DateTime.UtcNow.Subtract(start)}.  {tasks.Count(t => t.IsFaulted)} Failed");
            }
            await Task.WhenAll(tasks);
            Console.WriteLine($"All tasks finished in {DateTime.UtcNow.Subtract(start)}");
            Console.ReadKey();
        }
    }
}
`

Windows 10 Pro, Visual Studio 2017 15.7.3, SDK 2.1.300 and WindowsAzure.Storage 9.2.0

Happens with both .NET Core 2.0 & 2.1

It happens with both Cosmos DB [Canada Central] and regular Azure Table Storage [Central US].  

Happens with storage emulator, but I do not trust the results.  It feels different, as if it has problems for different reasons (for example, I got it to give me a 500 error code, which never happens on live Azure).  So I'd recommend investigating against a live storage account.

It happens when making requests QUICKLY.  For example, Task.WhenAll(create-a-bunch-of-requests) in debug mode did not create them fast enough for an error to occur (which made this problem quite annoying to reproduce *grr*).  For this repo, I spawn 50 threads to create a total of 12500 tasks as quickly as possible, which was effective (at least on my machine) in reproducing the problem.

Sometimes it runs normally, so try it out 3 or 4 times if there's no apparent problem.

wmengmsft - I will send you a direct message with my account name

^-- all related to .NET Core
\/-- below, .NET Framework

On .NET Framework (with the addition of ServicePointManager.DefaultConnectionLimit = 10000;), the problem still occurs. 

In a recent run, while it was stuck at 12499/12500 tasks completed, a "netstat" revealed 1018 connections to storage, all in "ESTABLISHED" state.

After 5 minutes, the last task threw this exception: Microsoft.WindowsAzure.Storage.StorageException: 'The client could not finish the operation within specified timeout.'

`
Stack trace:
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\dotnet-nov17\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndExecute(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\dotnet-nov17\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 96
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass2`1.<CreateCallback>b__0(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\dotnet-nov17\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp2.Program.<Main>d__0.MoveNext() in C:\Users\josh\Source\Repos\tests\ConsoleApp2\Program.cs:line 50
`

**Comment by joshlang** [comment]
I've abandoned this and moved to a different solution.  Thanks anyway.

**Comment by joshlang** [comment]
I take it back.  Cosmos DB tables are the best solution for us.  Reopening this issue.
