### ISSUE TITLE
parameterized IN query not working with CosmosDB .Net SDK

### ISSUE THREAD

**Issue by PankajRawat333** [Azure/azure-cosmos-dotnet-v2#614]
IN query return 0 record when passing parameter using SqlParameterCollection. the same query return records when passing parameter value inline string.

Scenario1

`var serialNumberList = $"'{string.Join("','", serialNumber)}'";`
`var query = new SqlQuerySpec("select * FROM c where c.ApplicationName = 'Eroutes' and c.Device[0].SerialNumber IN (@SerialNumber) ",
                       new SqlParameterCollection(new SqlParameter[] {
                   new SqlParameter { Name = "@SerialNumber", Value =  serialNumberList }
                       }));`

`dynamic result = client.CreateDocumentQuery<dynamic>(
                         UriFactory.CreateDocumentCollectionUri(appConfiguration.DatabaseId, AMSConstraints.MasterData),query)
                         .AsEnumerable().ToList();
            if (result != null && result.Count > 0)`

I'm getting 0 record in result

Scenario2

`var serialNumberList = $"'{string.Join("','", serialNumber)}'";`
`dynamic result = client.CreateDocumentQuery<dynamic>(
                         UriFactory.CreateDocumentCollectionUri(appConfiguration.DatabaseId, AMSConstraints.MasterData),
                         "select * FROM c where c.ApplicationName = 'Eroutes' and c.Device[0].SerialNumber IN (" + serialNumberList + ")")
                         .AsEnumerable().ToList();
            if (result != null && result.Count > 0)`

I'm getting 2 record in result.

Both Query should return 2 record as per my database.

**Environment summary**
SDK Version: Microsoft.Azure.DocumentDB 2.1.0
OS Version : Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by eydelrivero** [comment]
I'm experiencing the same issue, any plans for solving this one?

**Comment by eydelrivero** [comment]
Nevermind! the problem and the solution are very well explained [here](https://stackoverflow.com/questions/44636971/where-in-with-azure-documentdb-cosmosdb-net-sdk/44639998#44639998).

**Comment by irriss** [comment]
Thanks for very useful advice.

If my serialNumber parameter is a complex structure such as

[ { id: '123', name: 'abc' }, { id: '789', name: 'xyz' } ] 

am I able to reference a particular field?

Something like 

`select * FROM c where c.ApplicationName = 'Eroutes' and ARRAY_CONTAINS(@SerialNumber[*].Id, c.Device[0].SerialNumber)` 

Appreciate you help
