### ISSUE TITLE
Invoke-AzureRmResourceAction ignores -Confirm settings

### ISSUE THREAD

**Issue by mike-daly** [Azure/azure-cosmos-dotnet-v2#621]
Running cmdlet to change the failover priority for CosmosDb in a script.  Script runs in PowershellISE.  I get prompted for confirmation (yes/no/suspend).  It appears that -Confirm is not honored.   That would be a bug.

    $failoverPolicies = @(
        @{"locationName"="East US2"; "failoverPriority"=0}, 
        @{"locationName"="Central US"; "failoverPriority"=1}, 
        @{"locationName"="West US"; "failoverPriority"=2}
    )
    Invoke-AzureRmResourceAction -Action failoverPriorityChange -ResourceType "Microsoft.DocumentDb/databaseAccounts" -ApiVersion "2015-04-08" -ResourceGroupName $resourceGroup -Name $dbName -Parameters @{"failoverPolicies"=$failoverPolicies} -Confirm:$false

**Expected behavior**
Expect the command to execute without a prompt.

**Actual behavior**
user is prompted for confirmation

**Environment summary**
SDK Version:  
OS Version:  windows 10, build 1809
PS C:\Users\mikeda> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.17763.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

module version:

PS C:\Users\mikeda> get-command invoke-azurermresourceaction

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Invoke-AzureRmResourceAction                       4.4.1      AzureRM.Resources

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by rodneyjoyce** [comment]
I can see the same issue - I have to use -Force instead. I don't think this is an issue with Cosmos - it's the Invoke-AzureRmResourceAction cmdlet

**Comment by j82w** [comment]
This isn't a Cosmos related issue. Please open an issue on th [Azure-PowerShell repo](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.Resources/help/Invoke-AzureRmResourceAction.md).
