### ISSUE TITLE
Bad Performance and Cost For: Query By PartitionKey + ORDER BY 

### ISSUE THREAD

**Issue by mayoatte** [Azure/azure-cosmos-dotnet-v2#633]
Hey folks.

It seems there is a performance and R/U cost to querying a collection by id AND having an order by. That sounds a bit odd but here's what we are using it for: we are trying to perform existence checks on document we are not sure exists hence the search. We sort results from query by a default hence the sort.

In any case, queries with the id specified and an order cost orders of magnitude more (and are also far slower) than queries with just the id. We're specifying the partition key through feed options in both cases.

**To Reproduce**
Here's  a query with just the id

![image](https://user-images.githubusercontent.com/29760620/48508104-4a196100-e813-11e8-8508-941327cf43a2.png)

Here's a query with the id and an order by specified

![image](https://user-images.githubusercontent.com/29760620/48507996-06265c00-e813-11e8-81c8-c55f20a08093.png)

**Expected behavior**

The second query should perform and cost the same as the first one in practice. The partition key (id) is in the query itself (and we also specify it in the feedoptions in code) and the where clause should have limited the results to just the one record. 
Are we missing something here?

**Actual behavior**

The second query is 4000 times more expensive (it's many times slower too). 

**Environment summary**

SDK Version: Microsoft.Azure.DocumentDB.Core 2.1.3
OS Version: Windows
Also happens in the portal.

Thanks.

**Comment by pouyactm** [comment]
I am experiencing the same symptoms, is there any update on this?

**Comment by j82w** [comment]
@bchong95 any ideas?

**Comment by bchong95** [comment]
This seems like an index collision issue. QueryMetrics can confirm. 

@j82w  please loop in Query Team oncall if further investigation is needed.

**Comment by pouyactm** [comment]
Is there anything that can be done on our side to resolve the issue or this need to be raised as a support request from the portal for further investigation?

**Comment by j82w** [comment]
You can look at the [query metrics](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-query-metrics#query-execution-metrics). This will also be needed for any investigation.

**Comment by pouyactm** [comment]
This is my query metrics.

![image](https://user-images.githubusercontent.com/47869764/59084212-ad005000-893d-11e9-93cb-4405857e473f.png)
