### ISSUE TITLE
CreateDocumentAsync not create document

### ISSUE THREAD

**Issue by 86simonepenna** [Azure/azure-cosmos-dotnet-v2#639]
Hello, 

I follow this article:
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-dotnetcore-get-started

When I arrive to insert document with function "CreateDocumentAsync", the result is "Created", but on azure explorer viewer there are only db and collection. Document there isn't;

Why?

I use .NET Core with nuget package  Microsoft.Azure.DocumentDB.Core 2.1.3

Thank you

**Comment by anw063** [comment]
@86simonepenna I seem to have the same issue as you. Have you solved this problem at all?

**Comment by j82w** [comment]
@anw063 are you using the [Azure portal data explorer](https://docs.microsoft.com/en-us/azure/cosmos-db/data-explorer#access-azure-cosmos-db-explorer)?  Do you see the database and collection that was created?

**Comment by anw063** [comment]
@j82w Yes I was using the Azure portal data explorer and only the db and collection were created. I think I figured it out though. It seems that my CosmosDB resource was created for MongoDB API, and I was using the DocumentDB (SQL) API to create the documents which weren't appearing in the database and collection. Switching over to the MongoDB API fixed it for me.
