### ISSUE TITLE
Results not getting returned after C# SDK upgrade from 1.22 to 2.00 

### ISSUE THREAD

**Issue by mohit-infy** [Azure/azure-cosmos-dotnet-v2#643]
**Describe the bug**
We have partitioned document db which is partitioned by client id. When we try to search a document with some criteria and cross partition query set to true, We are not getting the result. However through fiddler if I trace the request and by changing this header from "x-ms-documentdb-partitionkeyrangeid: +fULAM1wRwA=,0" to "x-ms-documentdb-partitionkeyrangeid: +fULAM1wRwA=,1" returns the result. 

**To Reproduce**
No Specific steps

**Expected behavior**
Ideally it should return the result. Why there is need to change the header value.

**Actual behavior**
No Result returned

**Environment summary**
SDK Version: User-Agent: documentdb-dotnet-sdk/2.0.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
OS Version Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by mohit-infy** [comment]
I came to know about this header value because from previous version "User-Agent: documentdb-dotnet-sdk/1.22.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0" which was working fine only that header value was the difference.

**Comment by kirankumarkolli** [comment]
Can you please try with latest version in DirectMode?
