### ISSUE TITLE
Support for document query with LINQ + Generics but return document

### ISSUE THREAD

**Issue by mark-manticore** [Azure/azure-cosmos-dotnet-v2#644]
**Is your feature request related to a problem? Please describe.**
I want to use LINQ to build a document query using IQueryable<T>. The result of that query I would like to be as Microsoft.Azure.Documents.Document or even plain JSON (instead of type T). The reason is I would like to do some transformations on the raw document before deserializing to a POCO instance. Building the query from a SQL string is not an option.

**Describe the solution you'd like**
It would be nice if IDocumentQuery<T>.ExecuteNextAsync() would provide an override to return raw json, a newtonsoft JObject, or a Microsoft.Azure.Documents.Document. Something like the following:
```
            var documentQuery = _documentClient.CreateDocumentQuery<MyClass>(_documentCollectionUri, feedOptions).Where(myclass => myclass.Foo == "bar").AsDocumentQuery();
            FeedResponse<Document> feedResponse = await documentQuery.ExecuteNextAsync<Document>();
            foreach (var document in feedResponse)
            {
                // Do something with the raw json document
            }
```

**Describe alternatives you've considered**
Using the DocumentClient.CreateDocumentQuery with the sql string override allows building a query without LINQ that returns a Document. This however relies on proper syntax of the string query as opposed to LINQ where its compile time safe.

**Additional context**
This is a building block for handling data migration. I should be able to fetch a raw JSON document from the database in any query format I prefer (in my case LINQ), do my own transformation on the data before deserializing it to my custom POCO.

**Comment by kirankumarkolli** [comment]
Can you please try [V3 SDK](https://www.nuget.org/packages/Microsoft.Azure.Cosmos) which has first class  stream support for query as well.
