### ISSUE TITLE
Expose SharedOfferThroughput on RequestOptions

### ISSUE THREAD

**Issue by kevinhillinger** [Azure/azure-cosmos-dotnet-v2#648]
We need a way to expose the shared offer throughput to be set on a container.

**Comment by ealsur** [comment]
@kevinhillinger To use Shared Throughput, you need to set the Throughput at the Database level when you create the Database. When you do that, you don't have to specify Throughput when creating a Container within that Database.

Please see:

* https://docs.microsoft.com/en-us/azure/cosmos-db/set-throughput#setting-throughput-on-a-database
* https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-provision-database-throughput#provision-throughput-using-net-sdk

```
//set the throughput for the database
RequestOptions options = new RequestOptions
{
    OfferThroughput = 400
};

//create the database
await client.CreateDatabaseIfNotExistsAsync(
    new Database {Id = databaseName},  
    options);
```
