### ISSUE TITLE
Linq To DocumentDb uses current culture to generate query

### ISSUE THREAD

**Issue by fgheysels** [Azure/azure-cosmos-dotnet-v2#651]
**Describe the bug**
When performing a query that contains a where clause that filters on a numeric property (a double for instance), a syntax error is being thrown.

The LINQ to DocumentDb provider seems to use the current culture settings when generating this query.
The decimal separator in my cultural settings (nl-BE) is a comma, and when I perform a query that contains a double literal in the where clause, the following error is given:

>One or more errors occurred. (Message: {"errors":[{"severity":"Error","location":{"start":54,"end":55},"code":"SC1001","message":"Syntax error, incorrect syntax near ','."}]}
ActivityId: 68fff165-3275-447c-a4d4-19970641f4ed, Microsoft.Azure.Documents.Common/2.1.0.0, Windows/10.0.14393 documentdb-netcore-sdk/2.2.1)

When I set the current culture to the `InvariantCulture` just before executing the query, the syntax error is not given and the query works as expected.

**To Reproduce**

```csharp

CultureInfo.CurrentCulture = new CultureInfo("nl-BE");

DocumentClient client =
    new DocumentClient(new Uri(Environment.GetEnvironmentVariable("CosmosEndpoint")),
                               Environment.GetEnvironmentVariable("CosmosKey"));

var collectionUri = UriFactory.CreateDocumentCollectionUri("testdb", "accounts");

var accounts = client.CreateDocumentQuery<Account>(collectionUri)
                     .Where(a => a.Amount > 50.15)
                     .ToList();
```
The above code snippet will throw the syntax error.
I've captured the query that is being sent to CosmosDb using Fiddler, and this is the query that is being sent to CosmosDb:

```
{"query":"SELECT VALUE root FROM root WHERE (root[\"Amount\"] > 50,15) "}
```
Notice the comma that is being used as the decimal separator.

When I explicitly specify that the current culture is the invariant-culture, the query is generated as expected:

```csharp

CultureInfo.CurrentCulture = new CultureInfo.InvariantCulture;

DocumentClient client =
    new DocumentClient(new Uri(Environment.GetEnvironmentVariable("CosmosEndpoint")),
                               Environment.GetEnvironmentVariable("CosmosKey"));

var collectionUri = UriFactory.CreateDocumentCollectionUri("testdb", "accounts");

var accounts = client.CreateDocumentQuery<Account>(collectionUri)
                     .Where(a => a.Amount > 50.15)
                     .ToList();
```

With the above code, the query that is sent to CosmosDb looks like this:

```
{"query":"SELECT VALUE root FROM root WHERE (root[\"Amount\"] > 50.15) "}
```

**Expected behavior**
I expect that a syntactical correct query is generated, regardless the cultural settings of the client.

**Actual behavior**
Cultural settings are taken into account when generating a query.

**Environment summary**
SDK Version: Microsoft.Azure.DocumentDB.Core 2.2.1
OS Version: Windows 10

**Comment by rasmuschristensen** [comment]
I just ran into this issue too using spatial queries using

**Environment summary**
SDK Version: Microsoft.Azure.DocumentDB.Core 2.2.2
OS Version: Windows 10
Regional Settings Danish

When I add documents to a collection with Point (Microsoft.Azure.Documents.Spatial) the CurrentCulture it not used and the document is stored using "." as expected. 

When I make a query with .Distance, the current culture of my machine (danish) is used. This results in "," being used.

I was able to verify this by the generated query:

SELECT VALUE ST_DISTANCE(root[\"MeetingPoint\"], {\"type\": \"Point\", \"coordinates\": [9,71758, 55,529514]}) FROM root

If this is not a bug, what is the recommended usage?

**Comment by rasmuschristensen** [comment]
@fgheysels I wrote about my findings here and some workarounds
https://blog.rasmustc.com/cosmosdb-spatial-queries-and-linq-culture/

**Comment by bchong95** [comment]
There is a bug where the .ToString() code for queries doesn't use InvariantCulture. I will fix this and it will make it to the next release of the SDK.

**Comment by fgheysels** [comment]
I think this can be closed then.
