### ISSUE TITLE
BulkExecutor incomplatible with current verson of DocumentDB 2.2.1 Nuget package

### ISSUE THREAD

**Issue by matthewacme** [Azure/azure-cosmos-dotnet-v2#670]
Not sure if this is a Nuget issue, or a nuget package issue, or is this an actual hard requirement. I've upgraded to the current release of Microsoft.Azure.DocumentDB v 2.2.1 but the nuget package for the bulkexecutor is saying it needs to be Microsoft.Azure.DocumentDB v 2.1.3

this appears to be a continuation of #557 and #618

Severity Warning
Code NU1608
Description Detected package version outside of dependency constraint: Microsoft.Azure.CosmosDB.BulkExecutor 1.4.0 requires Microsoft.Azure.DocumentDB (= 2.1.3) but version Microsoft.Azure.DocumentDB 2.2.0 was resolved.

**Comment by ealsur** [comment]
This is by design, it's not a Nuget issue. The Bulk Executor has a hard dependency (equal version, not equal or higher).

So on the latest version of the Bulk Executor you can only use version 2,1,3 of the SDK.
