### ISSUE TITLE
Stored Procedure:The requested resource is no longer available at the server.

### ISSUE THREAD

**Issue by Gaploid** [Azure/azure-cosmos-dotnet-v2#671]
**Describe the bug**
"The requested resource is no longer available at the server."
The error is not consistent and I receive that error time to time, probably 1 time per 50 calls. I do not delete or replacing anything at all. Only making upsert documents using bulkimport.js stored procedure. Before creating the stored procedure I'm checking its existence using query and it seems sometimes the query returning that the procedure is absent but its not and sometimes I'm hitting that error below. 

Message: {"Errors":["The requested resource is no longer available at the 
server."]}
ActivityId: 0f0204fd-9773-48d0-89b9-684ddb889040, Request URI: /apps/dc58a7d8-2c2d-4965-9b37-a5473a155ec9/services/04eb7af4-4681-42ff-915b-f058d8c075f3/partitions/c7683cfa-22f5-4cd7-8345-fcbdef6ac5f6/replicas/131938316500455763s/, RequestStats: 
RequestStartTime: 2019-02-05T12:46:07.8258506Z, Number of regions attempted: 1
ResponseTime: 2019-02-05T12:46:07.8458484Z, StoreReadResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd17.documents.azure.com:14056/apps/dc58a7d8-2c2d-4965-9b37-a5473a155ec9/services/04eb7af4-4681-42ff-915b-f058d8c075f3/partitions/c7683cfa-22f5-4cd7-8345-fcbdef6ac5f6/replicas/131938316500455763s/, LSN: 0, GlobalCommittedLsn: 0, PartitionKeyRangeId: , IsValid: True, StatusCode: 410, IsGone: True, IsNotFound: False, IsInvalidPartition: True, RequestCharge: 0, ItemLSN: -1, SessionToken: , ResourceType: Collection, OperationType: Read
, SDK: Microsoft.Azure.Documents.Common/2.1.0.0, Windows/10.0.14393 documentdb-netcore-sdk/2.2.1

**To Reproduce**
I'm using Azure functions 2.0 (.net core) to upsert documents to partitioned cosmosdb(SQL) using the stored procedure (bulkimport.js) 

**Environment summary**
SDK Version: Microsoft.Azure.DocumentDB.Core  ver2.2.1
Azure functions 2.0 (Microsoft.NETCore.App 2.1), Microsoft.NET.Sdk.Functions ver 1.0.24

**Comment by ealsur** [comment]
@Gaploid According to the ActivityId you shared and the time range it happened, your collection `DebugAzureRates` was deleted and recreated with the same name.

**Comment by Gaploid** [comment]
@ealsur Yep, I've deleted it manually but that was 10mins before I`ve started the test and a lot of other same requests was finished successfully in parallel in that time. In the code, I'm trying to create database, collection and procedure if it exists then I am catching the exception and start the upload process, therefore everything should be there in place. As I said it starts failing 1 time from 50 with 3-5 requests in parallel.

**Comment by ealsur** [comment]
@Gaploid If I understand correctly, your Azure Function will create the DB, collection, and SP. Then execute the SP, which would just do the Upload?

And the error is executing the SP? Because by the error it looks like it's a Read on the Collection.

Do you have any recent error traces? A full stack trace would help if possible too.

**Comment by Gaploid** [comment]
Yes, you are correct.
It seems something wrong with parallel work with partitions and executing bulkimport.js procedure (https://github.com/Azure/azure-cosmosdb-js-server/blob/master/samples/stored-procedures/BulkImport.js) in CosmosDB. I remove parallel uploading and it seems right now is ok.

**Comment by ealsur** [comment]
According to that Stored Procedure code, it does a Collection Read (when it [gets the self link](https://github.com/Azure/azure-cosmosdb-js-server/blob/master/samples/stored-procedures/BulkImport.js#L8)).
If the collection is recreated as I've seen in the logs while one of these parallel executions is happening, it might generated the 404.

Just to close on this, make sure no collection deletions/recreations are happening during the process, or you can catch the 404 on those operations and retry it if collection recreations are expected.
