### ISSUE TITLE
Cassandra Materialized Views

### ISSUE THREAD

**Issue by Cephei** [Azure/azure-cosmos-dotnet-v2#672]
In prototyping with CosmosDB, I quickly uncovered a need for [materialized views](https://docs.microsoft.com/en-us/azure/architecture/patterns/materialized-view).

It would be most beneficial if we could use Cassandra's `CREATE MATERIALIZED VIEW` ([link](http://cassandra.apache.org/doc/4.0/cql/mvs.html)) command to provision a new table in CosmosDB. Internally, I'm guessing CosmosDB (via the `Change Feed Stream`) could automatically attach a listener - perhaps an `Azure Function` that updates the materialized view upon any changes to the source table.

1. Are there any plans to support this CQL command / backing infrastructure?
2. Is [this MSDN article](https://blogs.msdn.microsoft.com/premier_developer/2018/11/14/synchronizing-azure-cosmos-db-collections-for-blazing-fast-queries) the current recommended approach?
3. Are there any other solutions you might recommend?

**Comment by ealsur** [comment]
@Cephei Could you direct your question to askcosmosdb@microsoft.com? This issue doesn't seem related to the .NET SQL SDK.

**Comment by ealsur** [comment]
Please reopen if you have any .NET SQL SDK related inquiry / bug / code to share and report.
