### ISSUE TITLE
[BUG] LINQ provider: double serializing should be Culture Invariant

### ISSUE THREAD

**Issue by rlreis90** [Azure/azure-cosmos-dotnet-v2#681]
**Describe the bug**
For NuGet package versions >= 2.2.0, the LINQ provider serializes doubles (and probably decimals, etc) using the machine's culture, when it should be culture invariant. This is because decimal separators in Cosmos DB are always periods, but some cultures use commas.

**To Reproduce**
Install NuGet package version >= 2.2.0. Wirte a LINQ query any property which is a decimal/double (xxx.yy) in CosmosDB. Change culture to a region where decimal separators are commas (e.g. Brazil). Run the application. It should fail with a syntax error in the query.

**Expected behavior**
The query should function normally as it always did prior to version 2.2.0.

**Actual behavior**
It fails with a syntax error in the query (because a comma was placed where a dot should be).

**Environment summary**
SDK Version: >= 2.2.0
Windows

**Comment by khdang** [comment]
This is the same issue as reported in https://github.com/Azure/azure-cosmos-dotnet-v2/issues/651. Let's use it for tracking.
