### ISSUE TITLE
ForbiddenException with Authorization Token doesn't present sufficient permissions to serve the request

### ISSUE THREAD

**Issue by simon01** [Azure/azure-cosmos-dotnet-v2#688]
**Describe the bug**
I was using the code in this repository to create documents in cosmos db but I keep getting ForbiddenException with "Authorization Token doesn't present sufficient permissions to serve the request".

After a new collection gets created, I keep getting this error when CreateDocumentAsync gets called. However, it started working a few minutes later. 

This error only happens when Direct mode is used. However, it works perfectly fine when Gateway mode is used.

**To Reproduce**
Set ConnectionMode to ConnectionMode.Direct

**Expected behavior**
We should be able to create document straight after a new collection gets created.

**Actual behavior**
After a new collection gets created, we keep getting ForbiddenException with "Authorization Token doesn't present sufficient permissions to serve the request" when CreateDocumentAsync gets called.

**Environment summary**
SDK Version: v2.2.3
OS Version: Windows

**Additional context**
It mentioned "Each DocumentClient instance is thread-safe and performs efficient connection management and address caching when operating in Direct Mode." (https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips)
Does that mean the sdk cache collections somehow in Direct mode? If that's the case, is there any way to flush the cache so that I can access a new collection as soon as it gets created?

**Comment by justinbhopper** [comment]
Coincidentally, I have begun receiving this error too for brand new collections.  It takes several minutes before the collection is writable, and before that I keep receiving a ForbiddenException.  We too are using Direct mode.  I'm uncertain if this error was occurring before, but the timing of this ticket coming up for someone else a day before I noticed it is suspicious.

**Comment by kirankumarkolli** [comment]
@simon01 client is thread safe. Credentials are at account level and caching is not an issue here. 
Are you using emulator or production end-pint? 

Please send mail to askcosmosdb[AT]microsoft.com with details for further troubleshooting.
