### ISSUE TITLE
Latest versions dependency issues with System.Net.Http

### ISSUE THREAD

**Issue by Yonisha** [Azure/azure-cosmos-dotnet-v2#694]
It seems that the latest versions has a dependency on System.Net.Http v4.3.4 which depends on dll System.Net.Http v4.1.1.3.

However, the library has a reference for dll System.Net.Http 4.2.0.0.

![image](https://user-images.githubusercontent.com/10218080/56278987-f091c700-610f-11e9-97a9-c90e1b679269.png)

Either remove the dependency on nuget System.Net.Http 4.3.4 or fix the dependency of docdb nuget.

SDK Version: you can see the issue in v2.3.0, however prev versions also have inconsistency in references.
.NET Framework - 4.6.1

**Comment by kirankumarkolli** [comment]
@Yonisha thanks for reporting it. 
@ausfeldt pleas look into it.

**Comment by ohadschn** [comment]
IMHO nothing should ever reference 4.2.0.0, as far as I can tell it's some internal version shipped with VS...

**Comment by ausfeldt** [comment]
Will be fixed in the next release.

**Comment by EranGon** [comment]
This issue still exists in both NuGet versions 2.4.0 (which has been unlisted) and 2.4.1, even though the changelog states that the issue has been resolved in 2.4.0

**Comment by kirankumarkolli** [comment]
Can you please try > 2.4.2 https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/2.4.2
Will update the release notes.
