### ISSUE TITLE
CollectionThroughputInfo empty

### ISSUE THREAD

**Issue by zhengwia** [Azure/azure-cosmos-dotnet-v2#702]
I'm trying to find out the minimum RU allowed for a collection, following instruction on 
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/cosmos-db/set-throughput.md

I called client.ReadOfferAsync which returned and OfferV2, looking into the class the only related property I found was  
offer.Content.CollectionThroughputInfo 

which is an internal property and also empty. 

Could you advise how to find the minimum allowed RU for a container pls?

**Comment by j82w** [comment]
Here is a sample: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.readofferasync?view=azure-dotnet
