### ISSUE TITLE
SDK Issue: Syntax error, incorrect syntax near 'DISTINCT'

### ISSUE THREAD

**Issue by armanik11** [Azure/azure-cosmos-dotnet-v2#703]
Microsoft.Azure.DocumentDB.Core - 1.10.0

.net core 2.1 application

Is this by design for these versions?

If yes, which version should I update to to get this supported?

Query:

"SELECT DISTINCT c.Value FROM c" - works fine on Azure Cosmos DB Portal but not via SDK

Came across this issue: https://github.com/Azure/azure-cosmos-dotnet-v2/issues/536
but still not very clear.

**Comment by khdang** [comment]
Yes, is it expected, you would need to upgrade to the newer version of the SDK for DISTINCT support.
