### ISSUE TITLE
Support for OFFSET LIMIT clause

### ISSUE THREAD

**Issue by dfbaskin** [Azure/azure-cosmos-dotnet-v2#705]
**Is your feature request related to a problem? Please describe.**
Yes, not being able to use the new OFFSET LIMIT clause feature in Cosmos DB.

**Describe the solution you'd like**
LINQ queries should support Skip/Take operations.

**Describe alternatives you've considered**
Manually paging through records (or server-side stored procs).

**Additional context**
Not sure when this feature went live:
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-query-reference#-offset-limit-clause

It would be very nice to use Skip and Take in LINQ queries that translate into the OFFSET LIMIT clause.  Is this the plan?

**Comment by manigandham** [comment]
This is supported in the new v3 SDK: https://github.com/Azure/azure-cosmos-dotnet-v3

**Comment by dfbaskin** [comment]
Thanks for the update!
