### ISSUE TITLE
Missing JsonSerialization parameter for Upsert/Replace

### ISSUE THREAD

**Issue by JohnLTaylor** [Azure/azure-cosmos-dotnet-v2#707]
Describe the bug
If the DocumentClient is created with a JsonSerializerSettings with DateFormatHandling set to MicrosoftDateFormat, then calls to Create the document correctly encode the string, but upsert and replace do not correctly encode the date.

The problem is that the function UpsertDocumentPrivateAsync in the call to DocumentServiceRequest.Create passes a default null for the JsonSerializerSettings param instead of call this.GetSerializerSettingsForRequest(options) like CreateDocumentPrivateAsync.

It also looks like ReplaceDocumentPrivateAsync is suffering from the same problem.

To Reproduce
Create a database client with a JsonSerializerSettings with DateFormatHandling set to MicrosoftDateFormat,. Call UpsertDocumentAsync with a document containing a date field

Expected behavior
The date field should be encoded with the MicrosoftDateFormat

Actual behavior
The date field is encoded with the default IsoDateFormat

Environment summary
SDK Version:
Found in 2.2.1
Verified in 2.4.0
Code checked in 3.0.0.10
OS Version Windows 10

See [PR 199](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/199) submitted for azure-cosmos-dotnet-v3

**Comment by kirankumarkolli** [comment]
ReplaceDocumentAsync does serialization when Document type is used. 
@JohnLTaylor can you please share the scenario where Doucment type is used? 
Repo code would be great.

**Comment by JohnLTaylor** [comment]
Here is my demo code to expose the formatting problems with Cosmosdb
https://github.com/JohnLTaylor/CosmosDbFormattingError

**Comment by j82w** [comment]
@JohnLTaylor can you try the latest [2.8.1](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/)? It should be fixed.

**Comment by JohnLTaylor** [comment]
My test code is now failing which is a great thing.  Thanks for the help!
