### ISSUE TITLE
Cosmos DB Rate limited while processing 

### ISSUE THREAD

**Issue by breddynet** [Azure/azure-cosmos-dotnet-v2#708]
**Describe the bug**

I am using cosmos db to process data from Function APP and we have throughput setup as 20k and still showing traffic in the region is rate limited and i see 

Avg Throughput /s*
334.82 RU/s
Avg Requests /s*
98.13
Data Size
1.28 GB
Index Size
625.02 MB

Regions running is EastUs2 and Central US.

Can you please help me on this

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Environment summary**

SDK Version:
OS Version (e.g. Windows, Linux, MacOSX): 

**Additional context**

**Comment by BenjaBobs** [comment]
Average rate might be `334.82 RU/s` but that could easily be the case if you have spikes of high throughput requests and then otherwise have a very low amount of traffic. I suggest looking total amount of RU's used in small chunks of time and see if any of it could possibly go above 20k.
