### ISSUE TITLE
client.CreateDocumentCollectionIfNotExistsAsync creates paths but not indexes with functions v2... and v1

### ISSUE THREAD

**Issue by rowana16** [Azure/azure-cosmos-dotnet-v2#709]
**Describe the bug**
When creating a indexing policy via the .net sdk and azure functions, Path is being created but cannot get the indexes to be created.
Using DocumentDB.Core 2.4.0
(dropping version down to 2.0.0 solved the issue)

**To Reproduce**
I Execute this self-contained method:
```
public async Task CreateAirlineCollectionAsync()
        {
            var flightsCollection = new DocumentCollection
            {
                Id = "Flights"
            };
            flightsCollection.PartitionKey.Paths.Add("/TailNumber");

            IndexingPolicy indexingPolicy = new IndexingPolicy();

            List<string> rangeIncludedPaths = new List<string>()
                {
                    "/meta/timestamp/?",
                    "/RecordStartDate/?",
                    "/AnalyticType/?",
                    "/meta/acid/?",
                    "/CsvName/?",
                    "/Table/?",
                    "/IsActive/?",
                    "/meta/file_path/?"
                };

            foreach (string currentPath in rangeIncludedPaths)
            {
                IncludedPath includedPath = new IncludedPath();
                includedPath.Path = currentPath;
                includedPath.Indexes = new Collection<Index>
                {
                    new RangeIndex(DataType.String) { Precision = -1 },
                    new RangeIndex(DataType.Number) { Precision = -1 }
                };

                indexingPolicy.IncludedPaths.Add(includedPath);
            }

            var excludedPath = new ExcludedPath();
            excludedPath.Path = "/*";

            indexingPolicy.ExcludedPaths.Add(excludedPath);

            flightsCollection.IndexingPolicy = indexingPolicy;
            var response = await _client.CreateDocumentCollectionIfNotExistsAsync(DbUri, flightsCollection, new RequestOptions { OfferThroughput = 400 });
            FlightCollectionUri = UriFactory.CreateDocumentCollectionUri(Db, response.Resource.Id);
        }
```

**Expected behavior**
Index Policy should look something like this:
```
{
    "indexingMode": "consistent",
    "automatic": true,
    "includedPaths": [
        {
            "path": "/*",
            "indexes": [
                {
                    "kind": "Range",
                    "dataType": "Number",
                    "precision": -1
                },
                {
                    "kind": "Range",
                    "dataType": "String",
                    "precision": -1
                },
                {
                    "kind": "Spatial",
                    "dataType": "Point"
                }
            ]
        }
    ],
    "excludedPaths": [
        {
            "path": "/\"_etag\"/?"
        }
    ]
}
```
**Actual behavior**
Instead I get this
```
{
    "indexingMode": "consistent",
    "automatic": true,
    "includedPaths": [
        {
            "path": "/meta/timestamp/?",
            "indexes": []
        },
        {
            "path": "/RecordStartDate/?",
            "indexes": []
        },
        {
            "path": "/AnalyticType/?",
            "indexes": []
        },
        {
            "path": "/meta/acid/?",
            "indexes": []
        },
        {
            "path": "/CsvName/?",
            "indexes": []
        },
        {
            "path": "/Table/?",
            "indexes": []
        },
        {
            "path": "/IsActive/?",
            "indexes": []
        },
        {
            "path": "/meta/file_path/?",
            "indexes": []
        }
    ],
    "excludedPaths": [
        {
            "path": "/*"
        },
        {
            "path": "/\"_etag\"/?"
        }
    ]
}
```

**Environment summary**

SDK Version:
.net.sdk.function (1.0.24)
documentdb.core (2.4.0)
Tried with a number of different Newtonsoft versions 9.0.1 to 10.0.3

**Additional context**
No Errors, Just Doesn't Create Indexes

**Comment by alainvezina** [comment]
Good morning

I have something similar.  I tried locally and on a real cosmos db.

Test with 2.4 

Emulator:  Index empty
Azure: Index empty

Test a previous version 2.1.3 and 2.3

Emulator:  Index created but with wrong type for hash
Azure:  Index created but with wrong type for hash

Also now by default _etag are excluded

**Comment by alainvezina** [comment]
Also I Used Fiddler to sniff the traffic and I see the call to the API seems to be with the right values.. So it's on the API side?

**Comment by alainvezina** [comment]
Still not work with 2.20 for me.  It does create index but dont respect an index as follow:

new IncludedPath
            {
                Path = "/accountId/?",
                Indexes = new Collection<Index> {
                    new HashIndex(DataType.String) { Precision = 3 },
                    new RangeIndex(DataType.Number) { Precision = -1 }
                }
            };

Generated on Azure this

includedPaths": [
        {
            "path": "/accountId/?",
            "indexes": [
                {
                    "kind": "Range",
                    "dataType": "String",
                    "precision": -1
                },
                {
                    "kind": "Range",
                    "dataType": "Number",
                    "precision": -1
                }
            ]
        },

**Comment by bchrisb** [comment]
@alainvezina I also have this problem.

Code to create collection:

`var documentCollection = new DocumentCollection
                {
                    Id = _collectionId,
                    UniqueKeyPolicy = new UniqueKeyPolicy
                    {
                        UniqueKeys = new Collection<UniqueKey>
                        {
                            new UniqueKey
                            {
                                Paths = new Collection<string>
                                {
                                    $"/{uniqueConstraintKey}"
                                }
                            }
                        }
                    },
                    IndexingPolicy = new IndexingPolicy
                    {
                        IndexingMode = IndexingMode.Consistent,
                        Automatic = true,
                        IncludedPaths = new Collection<IncludedPath>
                        {
                            new IncludedPath
                            {
                                Path = "/*",
                                Indexes = new Collection<Index>
                                {
                                    new RangeIndex(DataType.Number, precision: -1),
                                    new HashIndex(DataType.String, precision: 3)
                                }
                            }
                        }
                    }
                };

                var resourceResponseDocumentCollection = await _client.CreateDocumentCollectionAsync(UriFactory.CreateDatabaseUri(_databaseId), documentCollection, new RequestOptions { OfferThroughput = offerThroughput })`

`{
    "indexingMode": "consistent",
    "automatic": true,
    "includedPaths": [
        {
            "path": "/*",
            "indexes": [
                {
                    "kind": "Range",
                    "dataType": "Number",
                    "precision": -1
                },
                {
                    "kind": "Range",
                    "dataType": "String",
                    "precision": -1
                }
            ]
        }
    ],
    "excludedPaths": [
        {
            "path": "/\"_etag\"/?"
        }
    ]
}`

Any ideas?

**Comment by antonsw** [comment]
Bump on this issue?

The same problem exists with Microsoft.Azure.Documents.Client

**Comment by Shawngbk** [comment]
There exists “path” and “indexes” in the indexing policy JSON.
Only the “path” will need to be cared in current status.
As for the “indexes”, it includes three attributes “kind”, “dataType” and “precision”.
Both of three attributes are not exposed to user anymore which is by design.
All fields in the “indexes” that are included support both numbers and string all full range precision(-1).

As part of the SDK and Portal upgrade, we are evolving the index policy to align with a new index layout we have rolled out to new containers. With this new layout, all primitive data types are indexed as Range with full precision (-1). Therefore, the index kinds and precision are not exposed to the user anymore. In the future, users will need to simply add paths to the includedPaths section, and ignore indexKinds and precision. This change has no impact on performance and you can continue to update indexing policy using the same syntax. You can continue to use all samples in our existing documentation to update index policy.

The upgrade has been done. These is no action required for customer side.
This change has no impact on performance and you can continue to update indexing policy using the same syntax. 

Reference document
=================
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-manage-indexing-policy
https://docs.microsoft.com/en-us/azure/cosmos-db/index-policy#obsolete-attributes
