### ISSUE TITLE
Cosmosdb Emulator and SDK conflicts

### ISSUE THREAD

**Issue by srivathsanvlb** [Azure/azure-cosmos-dotnet-v2#713]
**Bug**

In the https://aka.ms/cosmosdb-emulator link, the latest version of emulator available is 1.22.0
For that version the .net cosmos db sdk that was found to be working is Microsoft.Azure.DocumentDB.Core 2.0.0. The latest SDK version is 2.4.0, it is not working with the latest emulator.

**To Reproduce**
In a Simple console .net core console app, install the Microsoft.Azure.DocumentDB.Core 2.4.0 SDK. Install the latest emulator available which is 1.22.0 from https://aka.ms/cosmosdb-emulator.
Use the below code in Void Main.

public static string CosmosDBEndpoint = "https://localhost:8081";
        public static string CosmosDBKey = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";
using (var client = new DocumentClient(new Uri(CosmosDBEndpoint), CosmosDBKey))
            {
var databases = client.CreateDatabaseQuery().ToList();
            foreach (var database in databases)
            {
                Console.WriteLine($" Database Id: {database.Id}; Rid: {database.ResourceId}");
            }
}

**Expected behavior**
The above code should work and give the list of Databases.

**Actual behavior**
Exception:
Invalid API version. Ensure a valid x-ms-version header value is passed. Please update to the latest version of Azure Cosmos DB SDK.
ActivityId: 9e749572-fa47-4829-89e1-2afed809358e, Microsoft.Azure.Documents.Common/1.22.0.0, Windows/10.0.17134 documentdb-netcore-sdk/2.4.0

**Environment summary**

SDK Version:  2.4.0
Emulator version: 1.22.0
OS Version (e.g. Windows, Linux, MacOSX):  Windows 10

**Additional context**
Need a clear list depicting the Cosmos db SDK Version against the local emulator version.
Need a website that would let us download any version of the emulator

**Comment by KalyanChanumolu-MSFT** [comment]
The latest emulator version is 2.2.2.0
Are you sure you are using 1.22.0?

![image](https://user-images.githubusercontent.com/8835012/59213772-3da38e00-8bd3-11e9-900b-8bcac3d68d94.png)

**Comment by srivathsanvlb** [comment]
I see now the msi I get from https://aka.ms/cosmosdb-emulator is azure-cosmosdb-emulator-2.2.2-85c0ba85.msi. I will check and update. Give me a day time.

**Comment by srivathsanvlb** [comment]
azure-cosmosdb-emulator-2.2.2 works fine with SDK 2.4.0. Thanks for your support. You can close the ticket.
