### ISSUE TITLE
Indexing policy not set when specified in creating collection

### ISSUE THREAD

**Issue by bchrisb** [Azure/azure-cosmos-dotnet-v2#714]
**Describe the bug**
Creating an indexing policy through the SDK does not apply to the collection when viewed in the portal or programmatically reading the collection.

**To Reproduce**
Create a new DocumentCollection:

	var documentCollection = new DocumentCollection
	{
		Id = _collectionId,
		UniqueKeyPolicy = new UniqueKeyPolicy
		{
			UniqueKeys = new Collection<UniqueKey>
			{
				new UniqueKey
				{
					Paths = new Collection<string>
					{
						$"/{uniqueConstraintKey}"
					}
				}
			}
		},
		IndexingPolicy = new IndexingPolicy
		{
			IndexingMode = IndexingMode.Consistent,
			Automatic = true,
			IncludedPaths = new Collection<IncludedPath>
			{
				new IncludedPath
				{
					Path = "/*",
					Indexes = new Collection<Index>
					{
						new RangeIndex(DataType.Number, precision: -1),
						new HashIndex(DataType.String, precision: 3)
					}
				}
			}
		}
	};

	var resourceResponseDocumentCollection = await _client.CreateDocumentCollectionAsync(UriFactory.CreateDatabaseUri(_databaseId), documentCollection, new RequestOptions { OfferThroughput = offerThroughput });

Creates a collection with the following **incorrect** Indexing Policy (viewed via portal):

	{
		"indexingMode": "consistent",
		"automatic": true,
		"includedPaths": [
			{
				"path": "/*",
				"indexes": []
			}
		],
		"excludedPaths": [
			{
				"path": "/\"_etag\"/?"
			}
		]
	}

**Expected behavior**
Expected Indexing Policy:

	{
		"indexingMode": "consistent",
		"automatic": true,
		"includedPaths": [
			{
				"path": "/*",
				"indexes": [
					{
						"kind": "Range",
						"dataType": "Number",
						"precision": -1
					},
					{
						"kind": "Hash",
						"dataType": "String",
						"precision": 3
					}
				]
			}
		],
		"excludedPaths": []
	}

**Environment summary**

SDK Version: Microsoft.Azure.DocumentDB.Core v2.4.0 (latest at time of writing this)
OS Version (e.g. Windows, Linux, MacOSX):  Windows 10 Enterprise

**Additional context**
No errors - just incorrect policy.

**Comment by kirankumarkolli** [comment]
@bchrisb can you please send mail to askcosmosdb[AT]microsoft.com and team will follow-up.
