### ISSUE TITLE
Microsoft.Azure.Documents.Client.ResourceResponseBase is not IDisposable

### ISSUE THREAD

**Issue by StenPetrov** [Azure/azure-cosmos-dotnet-v2#716]
The class has a disposable field
`    internal DocumentServiceResponse response;`
Getting that field disposed of via`using` is not possible.

`ResourceResponseBase.ResourceStream` can be disposed of and leaves the class in an inconsistent state.

Side note: this is an SDK, `internal`, `private` and `sealed` mostly cause usability, testability and extensibility issues.

**Comment by j82w** [comment]
@StenPetrov regarding the usability check out the new [v3 SDK](https://github.com/Azure/azure-cosmos-dotnet-v3)

**Comment by kirankumarkolli** [comment]
V3 SDK first class stream support and is recommended for such scenarios.
