### ISSUE TITLE
Microsoft.Azure.Documents.NotFoundException: Entity with the specified id does not exist in the system., Windows/10.0.14393 documentdb-netcore-sdk/2.3.0

### ISSUE THREAD

**Issue by adrianknight89** [Azure/azure-cosmos-dotnet-v2#718]
I'm getting this issue every once in a while. I noticed this seems to happen when I attempt to query documents in a newly created container via `CreateDocumentQuery()` (e.g. programmatically create several containers and query them in the next 5-10 seconds). It seems the query aggregator isn't ready. My queries are executed through LINQ.

> "System.AggregateException: One or more errors occurred. (Entity with the specified id does not exist in the system., Windows/10.0.14393 documentdb-netcore-sdk/2.3.0) ---> Microsoft.Azure.Documents.NotFoundException: Entity with the specified id does not exist in the system., Windows/10.0.14393 documentdb-netcore-sdk/2.3.0\r\n   at Microsoft.Azure.Documents.Query.DocumentProducer`1.BufferMoreDocuments(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducer`1.BufferMoreIfEmpty(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducer`1.MoveNextAsyncImplementation(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducer`1.MoveNextAsync(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.MoveNextAsyncImplementation(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.ExecuteWithSplitProofing(Func`2 function, Boolean functionNeedsBeReexecuted, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.MoveNextAsync(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.ParallelDocumentQueryExecutionContext.DrainAsync(Int32 maxElements, CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.ExecutionComponent.AggregateDocumentQueryExecutionComponent.DrainAsync(Int32 maxElements, CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.ExecuteNextAsync(CancellationToken token)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.GetEnumerator()+MoveNext()\r\n   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at Microsoft.Azure.Documents.Linq.DocumentQueryProvider.Execute[TResult](Expression expression)\r\n   at System.Linq.Queryable.Count[TSource](IQueryable`1 source, Expression`1 predicate)\r\n   at MyServer.Functions.Triggers.FollowerTrigger.PushNotificationsAsync(List`1 insertList)\r\n   at MyServer.Functions.Triggers.FollowerTrigger.RunAsync(IReadOnlyList`1 documents, ExecutionContext executionContext) in C:\\My\\MyServer\\MyServer\\Functions\\Triggers\\MyTrigger.cs:line 51\r\n---> (Inner Exception #0) Microsoft.Azure.Documents.NotFoundException: Entity with the specified id does not exist in the system., Windows/10.0.14393 documentdb-netcore-sdk/2.3.0\r\n   at Microsoft.Azure.Documents.Query.DocumentProducer`1.BufferMoreDocuments(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducer`1.BufferMoreIfEmpty(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducer`1.MoveNextAsyncImplementation(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducer`1.MoveNextAsync(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.MoveNextAsyncImplementation(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.ExecuteWithSplitProofing(Func`2 function, Boolean functionNeedsBeReexecuted, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.MoveNextAsync(CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.ParallelDocumentQueryExecutionContext.DrainAsync(Int32 maxElements, CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.ExecutionComponent.AggregateDocumentQueryExecutionComponent.DrainAsync(Int32 maxElements, CancellationToken token)\r\n   at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.ExecuteNextAsync(CancellationToken token)<---\r\n"

**Comment by adrianknight89** [comment]
Based on https://github.com/Azure/azure-cosmos-dotnet-v2/issues/654#issuecomment-505065540, it looks like the race condition issue has not been addressed yet for `CreateDocumentQuery()`.

**Comment by kirankumarkolli** [comment]
Latest V3 address the issue. Please try https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.0.0-rc1
