### ISSUE TITLE
IsDefined Extension unable to use in unit testing

### ISSUE THREAD

**Issue by d1820** [Azure/azure-cosmos-dotnet-v2#719]
Describe the bug
Unable to mock, override or use IsDefined when writing unit tests.

To Reproduce
Try to use IsDefined() in a unit test.

Expected behavior
IsDefined() to be virtual or overrideable or default to return true when on the client

Actual behavior
IsDefined throws " throw new NotImplementedException();"

Environment summary
SDK Version: **2.1.3**
OS Version (e.g. Windows, Linux, MacOSX) **Windows**

Additional context
Once again the lack of exposing classes to be testable.

Microsoft.Azure.Documents.SystemFunctions
Assembly Microsoft.Azure.DocumentDB.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
microsoft.azure.documentdb.core\2.1.3\lib\netstandard1.6\Microsoft.Azure.DocumentDB.Core.dll

**Comment by kirankumarkolli** [comment]
IS_DEFINED is a system function which can used only in query. Ref: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-system-functions

IsDefined() is an extension method which enables typed/LINQ query generation. 
For UT there are two possibilities
1. Use LNIQ and execute query and validate the output
2. Use LINQ generate query and validate the query has IS_DEFINED

**Comment by d1820** [comment]
yeah i know what IS_DEFINED is and does.. point was from the client not testable even mocking through query's with link, cause its not extendable..

but thanks for the help and closing this..

**Comment by ChrisProlls** [comment]
Hi !
I've got the same problem here, I'm unable to test this methods.
Have you found any solution @d1820 ?

@kirankumarkolli 

- I can't validate the output because when the query is executed I got an `NotImplementedException`. My query is executed through a mocked `List<>` for my UT.

**Comment by d1820** [comment]
no solution, basically had to skip that section of testing.. i tried abstracting is_defined into my own wrapper which got the tests working but at runtime sdk errors out because Cosmo's didn't know how to process the abstraction.. so had to switch it all back.. if the client sdk just returned true instead of error all would be good..

**Comment by j82w** [comment]
The problem is C# static and extension methods don't support abstract or overrides. Even if you could over ride it in some way it's not possible to duplicate the logic in C#. For example x.address.id.IsDefined() would cause null ref exceptions in C# if address is null, but works perfectly in Cosmos query.
