### ISSUE TITLE
Cross Partition OFFSET / LIMIT is not supported

### ISSUE THREAD

**Issue by Elfocrash** [Azure/azure-cosmos-dotnet-v2#724]
**Is your feature request related to a problem? Please describe.**
Recently the offset and limit keywords were added in the Cosmos DB SQL and the v2 SDK. However when this same skip and take is performed using a cross partition query an error saying "Cross Partition OFFSET / LIMIT is not supported" is thrown. This is expected since it is described in the documentation as well here: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-offset-limit#remarks

Since Mark mentioned [here](https://github.com/MicrosoftDocs/azure-docs/issues/32328#issuecomment-509017824) that cross partition offset and limit will be coming in the v3 SDK I would like to ask for this feature to also be added in the v2 one since it is a very powerful feature. Many of us have a lot of code in production that could really benefit from it and it will be hard to justify putting a story in the sprint to rewrite our Cosmos data access code from scratch unless its 100% necessary. It wouldn't be reasonable to add it in v3 and not in v2, unless you want to force people out of the v2.

**Describe the solution you'd like**
It sounds like this is something that's code related on the SDK side, since Mark said that it will be added in the v3. Since the v3 is a v2 on steroids really, I can't see it being too hard to add, especially considering that you already added single partition offset and limit.

**Describe alternatives you've considered**
The alternative would be to just wait until this feature is added in v3 which is open source and just hack it into the v2 with some nasty reflection code.

**Comment by j82w** [comment]
@bchong95 is this already ported?

@Elfocrash v2 and v3 query pipelines are significantly different right now. We do have future plans to have v2 use the v3 pipeline, but that is still in the planning phase.

**Comment by bchong95** [comment]
The feature is in v3 already:

https://github.com/Azure/azure-cosmos-dotnet-v3/commit/77d1265335078c9bf72096d9df3bdf5120e82d84#diff-d86a721e2e0065d9ceef846d5f0b9aae

V2 needs to adopt some changes in how queries get executed in order to avoid breaking changes.

**Comment by bchong95** [comment]
This is fixed in 2.9.0
