### ISSUE TITLE
saving bool value in cosmosdb

### ISSUE THREAD

**Issue by bharatvijji** [Azure/azure-cosmos-dotnet-v2#725]
i am trying to save boolean value in cosmosdb, When i save the value as true i can see the property value as true but when i save the value as false the property is missing. Any help appritiated

**Comment by j82w** [comment]
@bharatvijji can you provide a repo? 

This works:
var item = await client.CreateDocumentAsync(collectionUri, new { id = "boolTest", booltest = false, pk = "test" });

**Comment by bharatvijji** [comment]
for created document Async i am sending the Entity Object and it;s not working 

await cosmosDbClient.CreateDocumentAsync(entityObj);

**Comment by j82w** [comment]
@bharatvijji  do you have any custom JSON serializer settings? Can you provide an example of the entity object?

**Comment by bharatvijji** [comment]
Thank you it's JSON Serializer settings  DefaultValueHandling as ignore and changed it to populate it's resolved
