### ISSUE TITLE
Invalid DistinctContinuationToken

### ISSUE THREAD

**Issue by SteeBono** [Azure/azure-cosmos-dotnet-v2#728]
Hi,

I'm trying to do a **DISTINCT** on **Cosmo DB (SQL API)** with **Pagination** (continuation token).

This is my code:

    var options = new FeedOptions
    {
        MaxItemCount = 3,
        EnableCrossPartitionQuery = true,
        RequestContinuation = string.IsNullOrWhiteSpace(continuationToken) ? string.Empty : continuationToken
    };

    var query = new SqlQuerySpec("SELECT DISTINCT VALUE m.customerNumber FROM m WHERE m.serviceNumber = @serviceNumber", new SqlParameterCollection
    {
        new SqlParameter("@serviceNumber", serviceNumber),
    });

    var customerNumbersQuery = await _cosmoClient.CreateDocumentQuery<string>(_messageCollectionLink, query, options).ToPagedResults<string>();
    var token = customerNumbersQuery.ContinuationToken;
    var customerNumbers = customerNumbersQuery.Results;

Where **ToPagedResults\<T\>** is an extension method like this:

    public static async Task<PagedResults<T>> ToPagedResults<T>(this IQueryable<T> source)
    {
        var documentQuery = source.AsDocumentQuery();
        var results = new PagedResults<T>();

        try
        {
            var queryResult = await documentQuery.ExecuteNextAsync<T>();
            if (!queryResult.Any())
            {
                return results;
            }
            results.ContinuationToken = queryResult.ResponseContinuation;
            results.Results.AddRange(queryResult);
        }
        catch (Exception ex)
        {
            //documentQuery.ExecuteNextAsync throws an Exception if there are no results
            return results;
        }

        return results;
    }

Instead **PagedResults\<T\>** is an object like this:

    public class PagedResults<T>
    {
        public PagedResults()
        {
            Results = new List<T>();
        }

        public string ContinuationToken { get; set; }

        public List<T> Results { get; set; }
    }

When I try to execute that query, I get this exception:

_Invalid DistinctContinuationToken: , Windows/10.0.17134 documentdb-netcore-sdk/2.4.0_

I can not find any documentation about that exception.

Thanks,
Stefano

**Comment by j82w** [comment]
Do you have the full exception message? Is it failing when you access the continuation token?

**Comment by SteeBono** [comment]
The exception only say ‘Invalid DistinctContinuationToken: , Windows/10.0.17134 documentdb-netcore-sdk/2.4.0’.

However that exception apper when I try to call the ‘ExecuteNextAsync’ method.

**Comment by SteeBono** [comment]
I have some news.

I have tried with the **SDK 3.0.0** making changes to the code.

	var options = new QueryRequestOptions
	{
	    MaxItemCount = 3
	};

	var query = new QueryDefinition("SELECT DISTINCT VALUE m.customerNumber FROM m WHERE m.serviceNumber = @serviceNumber")
	                                        .WithParameter("@serviceNumber", serviceNumber);

	continuationToken = string.IsNullOrWhiteSpace(continuationToken) ? string.Empty : continuationToken;
	var customerNumbersQuery = await _container.GetItemQueryIterator<string>(query, continuationToken, options).ToPagedResults<string>();

Where **ToPagedResults\<T\>** is an extension method like this:

   	public static async Task<PagedResults<T>> ToPagedResults<T>(this FeedIterator<T> source)
    {
        var results = new PagedResults<T>();

        try
        {
            var queryResult = await source.ReadNextAsync();
            if (!queryResult.Any())
            {
                return results;
            }
            results.ContinuationToken = queryResult.ContinuationToken;
            results.Results.AddRange(queryResult.Resource);
        }
        catch (Exception ex)
        {
            return results;
        }

        return results;
    }

When I try to execute that query, I get this exception:

	{{
	  "code": "BadRequest",
	  "message": "Invalid DistinctContinuationToken: , Windows/10.0.17134 cosmos-netstandard-sdk/3.0.0"
	}}

With this error:

	{
		"Response status code does not indicate success: 400 Substatus: 0 Reason: (Invalid DistinctContinuationToken: , Windows/10.0.17134 cosmos-netstandard-sdk/3.0.0)."
	}

Stacktrace:

	at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
	at Microsoft.Azure.Cosmos.CosmosResponseFactory.CreateQueryFeedResponse[T](ResponseMessage cosmosResponseMessage)
	at Microsoft.Azure.Cosmos.FeedIteratorCore`1.ReadNextAsync(CancellationToken cancellationToken)
	at WhatsappHub.FunctionApi.Extensions.ToPagedResults[T](FeedIterator`1 source) in C:\Consulcesi\WhatsappHub\WhatsappHub\WhatsappHub.FunctionApi\Extensions.cs:line 115


_I apologize in advance for the double post._
_I didn't know whether to open another issue on Fork 3.0.0._

Stefano

**Comment by j82w** [comment]
Why are you passing in string.empty? Can you try passing in null?

`continuationToken = string.IsNullOrWhiteSpace(continuationToken) ? string.Empty : continuationToken;`

**Comment by SteeBono** [comment]
I have tried with a null token and it worked!

Thanks,
Stefano
