### ISSUE TITLE
Linq Provider produces invalid SQL query when using deep-nested Any()/Where() clause with filters

### ISSUE THREAD

**Issue by countincognito** [Azure/azure-cosmos-dotnet-v2#758]
**Describe the bug**
I am using Microsoft.Azure.DocumentDB v2.5.1 (via Cosmonaut) with Linq to filter documents based on the contents of nested properties (**this issue seems to only happen with the nested properties are more than 1 level deep**). Specifically, when using Any() or Where() with filtering conditions the Linq Provider generates an invalid SQL query.

**To Reproduce**
The documents being queried resemble the following structure:

```
[
  {
    "Data": {
      "Readings": [
        {
          "Status": "valid"
        },
        {
          "Status": "invalid"
        }
      ]
    }
  },
  {
    "Data": {
      "Readings": [
        {
          "Status": "invalid"
        },
        {
          "Status": "invalid"
        }
      ]
    }
  }
]
```

When searching a queryable in the following way:

`entities.Where(x => x.Data.Readings.Any())`

the query produced is absolutely fine:

`{{"query":"SELECT VALUE root FROM root JOIN (SELECT VALUE COUNT(1) FROM root JOIN v0 IN root[\"Data\"][\"Readings\"] ) AS v1 WHERE (v1 > 0) "}}`

However, if I include a condition in the Any() clause:

`entities.Where(x => x.Data.Readings.Any(y => y.Status == "valid"))`

then the query produces invalid syntax:

`{{"query":"SELECT VALUE root FROM root JOIN (SELECT VALUE COUNT(1) FROM root JOIN 0 IN root[\"Data\"][\"Readings\"] WHERE (LOWER(0[\"Status\"]) = \"valid\") ) AS v0 WHERE (v0 > 0) "}}`

**Expected behavior**
Ideally, the query produced should look something like the following:

`{{"query":"SELECT VALUE root FROM root JOIN (SELECT VALUE COUNT(1) FROM root JOIN v0 IN root[\"Data\"][\"Readings\"] WHERE (LOWER(v0[\"Status\"]) = \"valid\") ) AS v1 WHERE (v1 > 0) "}}`

using an alias like "v0" instead of "0".

This query works perfectly fine against CosmosDb and produces the expected result.

**Actual behavior**
If I run the actual query that is produced:

`{{"query":"SELECT VALUE root FROM root JOIN (SELECT VALUE COUNT(1) FROM root JOIN 0 IN root[\"Data\"][\"Readings\"] WHERE (LOWER(0[\"Status\"]) = \"valid\") ) AS v0 WHERE (v0 > 0) "}}`

then Cosmos complains that there is a syntax error near the "0" alias (presumably because aliases that begin with numerical characters are invalid).

**Environment summary**

SDK Version: dotnet core 2.1 (v2.5.1 of Microsoft.Azure.DocumentDB)
OS Version (e.g. Windows, Linux, MacOSX): Windows 10 Pro

**Additional context**
I have tested this against Cosmos in the cloud and the latest Cosmos emulator - the same issue seems to occur for both.

I tried upgrading to Microsoft.Azure.Cosmos v3.3.2 library, but this didn't seem to fix the problem (https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1184).

**Comment by khdang** [comment]
Will track this issue in the V3 azure-cosmos-dotnet-v3 repo.

**Comment by countincognito** [comment]
@khdang Closed for the same reason listed in Azure/azure-cosmos-dotnet-v3#1184
