### ISSUE TITLE
Error occurs when using ThenBy in version 2.8.1

### ISSUE THREAD

**Issue by simonvane** [Azure/azure-cosmos-dotnet-v2#760]
According to https://github.com/Azure/azure-cosmos-dotnet-v2/blob/master/changelog.md#-270 support was added for ThenBy in version 2.7.0.

I am using version 2.8.1 but when I attempt to use ThenBy I get the following error:
`Microsoft.Azure.Documents.Linq.DocumentQueryException : Method 'ThenBy' is not supported., Windows/10.0.18362 documentdb-netcore-sdk/2.8.1`

(This happens whether running the query against version 2.9.0.0 of the Cosmos emulator or a "real" database in Azure)

**Comment by j82w** [comment]
@bchong95 any ideas?

**Comment by simonvane** [comment]
Any news on this?

**Comment by j82w** [comment]
@khdang any ideas?

**Comment by khdang** [comment]
Could you please upgrade to 2.9.0 or the latest version? This was due to an issue in the release process that the change wasn't properly maintained in 2.8.0 and 2.8.1. We'll take action to avoid this kind of issue.

**Comment by khdang** [comment]
Please kindly let us know if you still have this issue in 2.9.0 or later.

**Comment by simonvane** [comment]
I'd love to. Unfortunately several issues prevent me from doing this including the rather catastrophic introduction of a bug where FeedOptions.PartitionKey is not honoured - https://github.com/Azure/azure-cosmos-dotnet-v2/issues/757.

I don't feel like the 2.x line is getting the attention it deserves and it is going to take us a while to get to 3.x.
