### ISSUE TITLE
DocumentQuery.ExecuteNextAsync<T>(cancellationToken) doesn't map response to type <T> for query with GROUP BY

### ISSUE THREAD

**Issue by AnirvanK** [Azure/azure-cosmos-dotnet-v2#768]
---
name: DocumentQuery Exception for GROUP BY
about: Exception in ExecuteNextAsync in case of aggregate function(GROUP BY) in query
---

**Describe the bug**
We are using DocumentQuery.ExecuteNextAsync<T>(cancellationToken) to map query responses to the type provided as <T>. This works fine when query doesn't contain aggregate function(GROUP BY). However, when the query contains GROUP BY, we get the below error:

`Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert type 'Newtonsoft.Json.Linq.JObject' to '<T>'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.Azure.Documents.Client.FeedResponseBinder.Convert[T](FeedResponse`1 dynamicFeed)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.ExecuteNextPrivateAsync[TResponse](CancellationToken cancellationToken)`

We noticed that the method returns an object of type `System.Collections.Generic.List<object>`. In case of aggregate queries(GROUP BY), this list contains objects of type `Newtonsoft.Json.Linq.Jobject`. However, in case of queries without aggregate function(GROUP BY), it contains objects of type `Microsoft.Azure.Documents.QueryResult`. 
In the latter case, the response is mapped to the POCO absolutely fine, might be due to the availability of `jsonSerializer` implicitly within the `Microsoft.Azure.Documents.QueryResult` object.

**To Reproduce**
Query must contain aggregate function(GROUP BY) and the method `ExecuteNextAsync<T>` must be executed by passing a POCO as `<T>`.

**Expected behavior**
Irrespective of query containing aggregate functions or not, the ExecuteNextAsync<T>(cancellationToken) method should be able to map the query response to the object of type `<T>` provided.

**Actual behavior**
`Runtime Binder Exception - Cannot convert type 'Newtonsoft.Json.Linq.JObject' to '<T>'`

**Environment summary**
SDK Version: Microsoft.Azure.DocumentDB.Core 2.9.3
OS Version (e.g. Windows, Linux, MacOSX): MacOSX

**Comment by j82w** [comment]
This is now fixed. Please try the latest [2.10.1](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/2.10.1)
