### ISSUE TITLE
NullReferenceException when iterating DocumentQuery in IIS on V2.10.0

### ISSUE THREAD

**Issue by Jzrzmy** [Azure/azure-cosmos-dotnet-v2#774]
**Describe the bug**
After updating the Microsoft.Azure.DocumentDB.Core package to 2.10.0 we started getting null reference exceptions when querying document collections (with Android only).
After downgrading to V2.9.4, the exception went away.

**To Reproduce**
This bug seems to be back, a similar issue had been created => #750 with full info.
v2.10.0 reintroduced this bug (the same exception is thrown).

**Comment by j82w** [comment]
Working on a hotfix. The PR that caused this issue was not properly reverted in all the places.

**Comment by j82w** [comment]
@Jzrzmy [2.10.1](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/2.10.1) is released with the fix.

**Comment by Jzrzmy** [comment]
great ! Thank you
