### ISSUE TITLE
Microsoft.Azure.DocumentDB.Core Nuget Package 

### ISSUE THREAD

**Issue by Madison-Abegglen** [Azure/azure-cosmos-dotnet-v2#777]
The package is unable to download. Checking the nuget site, it has 0 downloads. Has no one noticed this?

**Comment by ealsur** [comment]
What is the error you are getting when trying to download it?

**Comment by ealsur** [comment]
For reference, other newly updated packages are also showing 0:
https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.14.0-beta3
![image](https://user-images.githubusercontent.com/1633401/76642256-1be38880-6510-11ea-91a0-92db8f70fe15.png)

This sounds like an issue on Nuget side.

@Madison-Abegglen What is the error you are getting when trying to download the package to assert that is undownloable?

**Comment by j82w** [comment]
I created an issue against Nuget.org for this issue. 
https://github.com/NuGet/NuGetGallery/issues/7869

**Comment by Madison-Abegglen** [comment]
When attempting to install via the Visual Studio 2019 package manager, I get "Found invalid data while decoding" in my output.

**Comment by ealsur** [comment]
Does using `dotnet add package Microsoft.Azure.Cosmos` work? I could not repro the issue on VS2019.

**Comment by ealsur** [comment]
The statistics were fixed on Nuget side, it seems it was an issue on Nuget.
![image](https://user-images.githubusercontent.com/1633401/76994621-e245bf80-690b-11ea-826e-e4302dc5ec26.png)
