### ISSUE TITLE
using GROUP BY not returning results with latest nuget Microsoft.Azure.DocumentDB.Core 2.10.1

### ISSUE THREAD

**Issue by keerthiadu** [Azure/azure-cosmos-dotnet-v2#783]
**Describe the bug**

Have a simple GROUP BY query, it used to work with 
Microsoft.Azure.DocumentDB.Core V 2.1.3

we just upgraded to 2.10.1 and the query stopped working.
**To Reproduce**

sample query:

`"SELECT root.name, MAX(root.version) AS version FROM root GROUP BY root.name OFFSET 0 LIMIT 20"`
sample snippet:

// where query is IDocumentQuery<dynamic>.
```
var response = await query.ExecuteNextAsync<dynamic>().ConfigureAwait(false);
results = response.AsEnumerable().ToList();
```

This is returning empty list.

Using fiddler, I was able to see the response coming from the backend

with 2.1.3
the response was
```
{
  "_rid": "d-kQANdnbAE=",
  "Documents": [
    {
      "name": "mango",
      "version": 10
    }
  ],
  "_count": 1
}
```

with 2.10.1
the response was
```
{
  "_rid": "d-kQANdnbAE=",
  "Documents": [
    {
      "groupByItems": [
        {
          "item": "mango"
        }
      ],
      "payload": {
        "name": "mango",
        "version": {
          "item": 10,
          "item2": {
            "max": 10,
            "count": 9
          }
        }
      }
    }
  ],
  "_count": 1
}
```
**Expected behavior**
We expect non empty list.
**Actual behavior**
we are getting empty list.
**Environment summary**

SDK Version: Microsoft.Azure.DocumentDB.Core 2.10.1
OS Version (e.g. Windows, Linux, MacOSX): WIndows

**Additional context**

**Comment by bchong95** [comment]
This looks like the correct behavior. GROUP BY was only added in 2.9.0, so that's when the payload support was there:

https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-dotnet#-290

Please reopen if you can provide the dataset that has the incorrect results.

**Comment by bchong95** [comment]
In this scenario you are not draining the pages fully so you are not getting the final result. The first page is always going to be empty. You should drain until the query has no more results.
