### ISSUE TITLE
with latest 2.10.1, using GROUP BY is not passing PartitionKey to the backend 

### ISSUE THREAD

**Issue by keerthiadu** [Azure/azure-cosmos-dotnet-v2#784]
**Describe the bug**
FeedOptions.ParitionKey is not being sent to the backend when using group by.

**To Reproduce**
populate PartitionKey on FeedOptions.
```
IDocumentQuery<dynamic> query = this.documentClient.CreateDocumentQuery<dynamic>(uri, sqlQuery, feedOptions).AsDocumentQuery();
if (query.HasMoreResults)
{
    var response = await query.ExecuteNextAsync<dynamic>().ConfigureAwait(false);
}

```
Using fiddler look at the request headers going to backend
x-ms-documentdb-partitionkey is missing

**Expected behavior**
x-ms-documentdb-partitionkey header must be set to the partitionKey specified in the feedOptions
**Actual behavior**

x-ms-documentdb-partitionkey header is not set.
**Environment summary**

SDK Version: 2.10.1
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Additional context**

**Comment by j82w** [comment]
@bchong95 can you take a look?

**Comment by bchong95** [comment]
Please share the full fiddler request and response.

**Comment by keerthiadu** [comment]
RAW REQUEST
`POST https://**REDACTED**/docs HTTP/1.1
Host: **REDACTED**.documents.azure.com
x-ms-continuation: 
x-ms-documentdb-isquery: True
x-ms-max-item-count: 2147483647
x-ms-documentdb-query-enablecrosspartition: False
x-ms-documentdb-responsecontinuationtokenlimitinkb: 6
x-ms-documentdb-populatequerymetrics: True
x-ms-documentdb-partitionkeyrangeid: d-kQANdnbAE=,0
x-ms-date: Thu, 07 May 2020 16:41:22 GMT
Authorization: **REDACTED**
x-ms-activity-id: 4e0e5344-86ae-41b1-bd68-19b26ee84d63
Cache-Control: no-cache
User-Agent: Windows/10.0.18363 documentdb-netcore-sdk/2.10.1
x-ms-version: 2018-09-17
Accept: application/json
x-ms-request-root-id: 00-6b09d60506dbff47945492fa695e6e44-4ac1542dfa1c4d45-00
x-ms-client-request-id: f189adb00cab4c3da8028addfa4ae711
x-ms-client-user-type: ApiUser
x-ms-client-subscription-id: 5f08d643-1910-4a38-a7c7-84a39d4f42e0
Request-Context: appId=cid-v1:b946426b-c5d7-422c-8395-f9215fe2c22e
Request-Id: |6b09d60506dbff47945492fa695e6e44.3368abee4c0ba54b.
traceparent: 00-6b09d60506dbff47945492fa695e6e44-3368abee4c0ba54b-00
Content-Type: application/query+json
Content-Length: 330

{"query":"SELECT [{\"item\": root.name}] AS groupByItems, {\"name\": root.name, \"version\": {\"item\": MAX(root.version), \"item2\": {\"max\": MAX(root.version), \"count\": COUNT(root.version)}}} AS payload\nFROM root\nWHERE (root.docType = @docType)\nGROUP BY root.name","parameters":[{"name":"@docType","value":"REDACTED"}]}`


RAW RESPONSE
`HTTP/1.1 200 Ok
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Type: application/json
Server: Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000
x-ms-last-state-change-utc: Wed, 29 Apr 2020 00:22:10.222 GMT
x-ms-continuation: +RID: **REDACTED**
x-ms-resource-quota: documentSize=10240;documentsSize=10485760;documentsCount=-1;collectionSize=10485760;
x-ms-resource-usage: documentSize=1202;documentsSize=1082132;documentsCount=567322;collectionSize=1231718;
lsn: 7964018
x-ms-item-count: 40190
x-ms-schemaversion: 1.9
x-ms-alt-content-path: **REDACTED**
x-ms-content-path: d-kQANdnbAE=
x-ms-xp-role: 2
x-ms-documentdb-query-metrics: totalExecutionTimeInMs=4705.82;queryCompileTimeInMs=0.26;queryLogicalPlanBuildTimeInMs=0.07;queryPhysicalPlanBuildTimeInMs=0.08;queryOptimizationTimeInMs=0.00;VMExecutionTimeInMs=4700.95;indexLookupTimeInMs=0.75;documentLoadTimeInMs=4030.84;systemFunctionExecuteTimeInMs=0.00;userFunctionExecuteTimeInMs=0.00;retrievedDocumentCount=142922;retrievedDocumentSize=257445010;outputDocumentCount=40190;outputDocumentSize=5656443;writeOutputTimeInMs=54.27;indexUtilizationRatio=0.00
x-ms-cosmos-query-execution-info: {"reverseRidEnabled":true,"reverseIndexScan":false}
x-ms-global-Committed-lsn: 7964017
x-ms-number-of-read-regions: 1
x-ms-transport-request-id: 109629
x-ms-cosmos-llsn: 7964018
x-ms-session-token: 0:-1#7964018
x-ms-request-charge: 18266.12
x-ms-serviceversion: version=2.10.0.0
x-ms-activity-id: 4e0e5344-86ae-41b1-bd68-19b26ee84d63
x-ms-gatewayversion: version=2.10.0
Date: Thu, 07 May 2020 16:41:27 GMT
Content-Length: 5656443

{"_rid":"d-kQANdnbAE=","Documents":[{"groupByItems":[{"item":"wow"}],"payload":{"name":"wow","version":{"item":1,"item2":{"max":1,"count":1}}}}, .....]}

Response contained items from all partitions, and partitionkey specified in the feedoptions got ignored.

**Comment by bchong95** [comment]
I submitted a fix in the internal code base. Expect this to be patched in the next SDK release.
