### ISSUE TITLE
Connection hanging (rather than throwing a SocketException) on connection to non-existing CosmosDB. 

### ISSUE THREAD

**Issue by johnm123** [Azure/azure-cosmos-dotnet-v2#799]
**Describe the bug**
I have some simple code which calls ReadDatabaseAsync. If I call this method when DocumentClient is configured against a bad endpoint, e.g. "http://localhost:1234" (no emulator running), I would expect an exception of some kind (probably SocketException) with 'connection refused'). Instead, the ReadDatabaseAsync call hangs (indefinitely?). I'm not aware of anything I'm doing wrong here as this is mainly boilerplate code. It's possible this is intentional with some sort of transient retry policy within the client.  

**To Reproduce**
var client = new DocumentClient(  
new Uri("https://localhost:1234"), "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==");

await client.ReadDatabaseAsync(UriFactory.CreateDatabaseUri("MyDbId"));

**Expected behavior**
SocketException thrown from: 
await client.ReadDatabaseAsync(UriFactory.CreateDatabaseUri("MyDbId"));

**Actual behavior**
Indefinite hang, no exception. 

**Environment summary**
SDK Version: .NET Core 3.1.101
OS Version (e.g. Windows, Linux, MacOSX):  Windows 10 Enterprise.
Microsoft.Azure.DocumentDB.Core 2.11.2

**Comment by j82w** [comment]
Please checkout this issue: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1635#issuecomment-646809294 . It's the same reason for both the v3 and v2 .NET SDKs.

**Comment by johnm123** [comment]
Yes, looks like this has already been discussed. Will close. Thanks for pointing me to it.
