### ISSUE TITLE
Unable to use Linq Queries with string.Contains non case sensitive

### ISSUE THREAD

**Issue by alexandrofll** [Azure/azure-cosmos-dotnet-v2#830]
Hello team,
I am unable to use Linq Queries with string.Contains for non case sensitive search.
Wondering if you are planning to add this anytime soon.

```
//linq query (Doesn't work with StringComparison)
x => x.field1.Contains(searchValue, StringComparison.InvariantCultureIgnoreCase)
```

```
//sql query
SELECT * FROM c WHERE CONTAINS(c.field1, searchValue, true)
```

Looks like a simple addition and it can provide a lot of value.
If there is any standard practice to do this, please point me into the right direction.

Currently I am being forced to do it using ToLower() and this is a performance overkilling.

```
//linq query
x => x.field1.ToLower().Contains(searchValue.ToLower())
```

**Comment by j82w** [comment]
This is supported in the [.NET v3 SDK](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#-3100---2020-06-18). @sboshra is there any plans to back ports this to v2 SDK?

**Comment by alexandrofll** [comment]
Thanks for the information. I have migrated to Cosmos SDK V3 and it works like a charm.
