### ISSUE TITLE
V2 SDK is not detecting new regions being added

### ISSUE THREAD

**Issue by ravibha** [Azure/azure-cosmos-dotnet-v2#852]
**Describe the bug**
While using multi-master with ConnectionMode as Gateway, Protocol as Tcp, the sdk is not detecting new regions being added.

**To Reproduce**
CosmosDB SDK setup:
`ConnectionPolicy connectionPolicy = new ConnectionPolicy()
            {
                 ConnectionMode = ConnectionMode.Direct,
                 ConnectionProtocol = Protocol.Tcp
                UseMultipleWriteLocations = true,
            };
            connectionPolicy.SetCurrentLocation(LocationNames.WestCentralUS);
            DocumentClient client = new DocumentClient(new Uri<cosmosdb uri>), "<somekey>”, connectionPolicy);`

On the server (with WestUS and EastUS) with multiple writes, do the following steps with cosmosdb client started all the time. Make sure traffic from the client is sent to WestUS.

1. Remove WestUS region. (All traffic goes to EastUS)
2. Add WestUS region back again.

**Expected behavior**
Traffic from WestUS should start flowing back to WestUS again.

**Actual behavior**
Traffic from WestUS still goes to EastUS.

**Environment summary**

SDK Version: 2.11.0
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Comment by ealsur** [comment]
Fixed in 2.17.0
