### ISSUE TITLE
V2 SDK executing queries on Gateway mode

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v2#854]
With the client configured in Direct mode, if the conditions are not met for the ServiceInterop DLL to be used (reference https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips#hosting-recommendations), the SDK needs to obtain the query plan from Gateway (HTTP request).

When that happens, the query execution is also sent through Gateway mode as an HTTP request instead of Direct mode honoring the client configuration.

It does not affect any other operation outside of Query.

**Comment by sourabh1007** [comment]
This issue is fixed in 2.16.1 version.
