### ISSUE TITLE
Using Managed Identity with `DocumentClient`

### ISSUE THREAD

**Issue by levimatheri** [Azure/azure-cosmos-dotnet-v2#874]
Is there a way to pass AAD token i.e. `TokenCredential` to `DocumentClient` for accessing Cosmos using Managed Identity?

**Comment by ealsur** [comment]
No, not in the DocumentClient. You need to use the V3 SDK for that: https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#initialize-the-sdk-with-azure-ad

**Comment by levimatheri** [comment]
Gotcha. Thought so. Thanks @ealsur
